// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voyage.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCarrierMovements = `-- name: DeleteCarrierMovements :exec
DELETE FROM carrier_movement WHERE voyage_id = $1
`

func (q *Queries) DeleteCarrierMovements(ctx context.Context, voyageID int64) error {
	_, err := q.db.Exec(ctx, deleteCarrierMovements, voyageID)
	return err
}

const existsVoyageByNumber = `-- name: ExistsVoyageByNumber :one
SELECT EXISTS (SELECT 1 FROM voyage WHERE voyage_number = $1)
`

func (q *Queries) ExistsVoyageByNumber(ctx context.Context, voyageNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, existsVoyageByNumber, voyageNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getVoyageByNumber = `-- name: GetVoyageByNumber :one
SELECT id, voyage_number, vessel_name, carrier, supported_cargo_types
FROM voyage WHERE voyage_number = $1
`

type GetVoyageByNumberRow struct {
	ID                  int64
	VoyageNumber        string
	VesselName          string
	Carrier             string
	SupportedCargoTypes string
}

func (q *Queries) GetVoyageByNumber(ctx context.Context, voyageNumber string) (GetVoyageByNumberRow, error) {
	row := q.db.QueryRow(ctx, getVoyageByNumber, voyageNumber)
	var i GetVoyageByNumberRow
	err := row.Scan(
		&i.ID,
		&i.VoyageNumber,
		&i.VesselName,
		&i.Carrier,
		&i.SupportedCargoTypes,
	)
	return i, err
}

const insertCarrierMovement = `-- name: InsertCarrierMovement :exec
INSERT INTO carrier_movement (
    voyage_id, departure_location_unlocode, arrival_location_unlocode,
    departure_date, arrival_date, seq_number
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCarrierMovementParams struct {
	VoyageID                  int64
	DepartureLocationUnlocode string
	ArrivalLocationUnlocode   string
	DepartureDate             pgtype.Timestamp
	ArrivalDate               pgtype.Timestamp
	SeqNumber                 int32
}

func (q *Queries) InsertCarrierMovement(ctx context.Context, arg InsertCarrierMovementParams) error {
	_, err := q.db.Exec(ctx, insertCarrierMovement,
		arg.VoyageID,
		arg.DepartureLocationUnlocode,
		arg.ArrivalLocationUnlocode,
		arg.DepartureDate,
		arg.ArrivalDate,
		arg.SeqNumber,
	)
	return err
}

const insertVoyage = `-- name: InsertVoyage :one
INSERT INTO voyage (voyage_number, vessel_name, carrier, supported_cargo_types)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertVoyageParams struct {
	VoyageNumber        string
	VesselName          string
	Carrier             string
	SupportedCargoTypes string
}

func (q *Queries) InsertVoyage(ctx context.Context, arg InsertVoyageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertVoyage,
		arg.VoyageNumber,
		arg.VesselName,
		arg.Carrier,
		arg.SupportedCargoTypes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCarrierMovements = `-- name: ListCarrierMovements :many
SELECT departure_location_unlocode, arrival_location_unlocode, departure_date, arrival_date, seq_number
FROM carrier_movement WHERE voyage_id = $1 ORDER BY seq_number
`

type ListCarrierMovementsRow struct {
	DepartureLocationUnlocode string
	ArrivalLocationUnlocode   string
	DepartureDate             pgtype.Timestamp
	ArrivalDate               pgtype.Timestamp
	SeqNumber                 int32
}

func (q *Queries) ListCarrierMovements(ctx context.Context, voyageID int64) ([]ListCarrierMovementsRow, error) {
	rows, err := q.db.Query(ctx, listCarrierMovements, voyageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCarrierMovementsRow
	for rows.Next() {
		var i ListCarrierMovementsRow
		if err := rows.Scan(
			&i.DepartureLocationUnlocode,
			&i.ArrivalLocationUnlocode,
			&i.DepartureDate,
			&i.ArrivalDate,
			&i.SeqNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoyages = `-- name: ListVoyages :many
SELECT id, voyage_number, vessel_name, carrier, supported_cargo_types
FROM voyage ORDER BY voyage_number
`

type ListVoyagesRow struct {
	ID                  int64
	VoyageNumber        string
	VesselName          string
	Carrier             string
	SupportedCargoTypes string
}

func (q *Queries) ListVoyages(ctx context.Context) ([]ListVoyagesRow, error) {
	rows, err := q.db.Query(ctx, listVoyages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoyagesRow
	for rows.Next() {
		var i ListVoyagesRow
		if err := rows.Scan(
			&i.ID,
			&i.VoyageNumber,
			&i.VesselName,
			&i.Carrier,
			&i.SupportedCargoTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoyage = `-- name: UpdateVoyage :exec
UPDATE voyage
SET vessel_name = $2, carrier = $3, supported_cargo_types = $4, updated_at = NOW()
WHERE voyage_number = $1
`

type UpdateVoyageParams struct {
	VoyageNumber        string
	VesselName          string
	Carrier             string
	SupportedCargoTypes string
}

func (q *Queries) UpdateVoyage(ctx context.Context, arg UpdateVoyageParams) error {
	_, err := q.db.Exec(ctx, updateVoyage,
		arg.VoyageNumber,
		arg.VesselName,
		arg.Carrier,
		arg.SupportedCargoTypes,
	)
	return err
}
