-- routingms local-h2 プロファイル用スキーマ
-- H2 2.x 対応（GENERATED BY DEFAULT AS IDENTITY）

-- Axon Framework が必要とするテーブル
CREATE TABLE IF NOT EXISTS tokenentry (
    processorname VARCHAR(255) NOT NULL,
    segment       INTEGER      NOT NULL,
    token         BINARY LARGE OBJECT,
    tokentype     VARCHAR(255),
    timestamp     VARCHAR(255),
    owner         VARCHAR(255),
    PRIMARY KEY (processorname, segment)
);

CREATE TABLE IF NOT EXISTS domainevententry (
    globalindex         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregateidentifier VARCHAR(255) NOT NULL,
    sequencenumber      BIGINT       NOT NULL,
    type                VARCHAR(255),
    eventidentifier     VARCHAR(255) NOT NULL UNIQUE,
    metadata            BINARY LARGE OBJECT,
    payload             BINARY LARGE OBJECT NOT NULL,
    payloadrevision     VARCHAR(255),
    payloadtype         VARCHAR(255) NOT NULL,
    timestamp           VARCHAR(255) NOT NULL,
    PRIMARY KEY (globalindex)
);

CREATE TABLE IF NOT EXISTS snapshotevententry (
    aggregateidentifier VARCHAR(255) NOT NULL,
    sequencenumber      BIGINT       NOT NULL,
    type                VARCHAR(255) NOT NULL,
    eventidentifier     VARCHAR(255) NOT NULL UNIQUE,
    metadata            BINARY LARGE OBJECT,
    payload             BINARY LARGE OBJECT NOT NULL,
    payloadrevision     VARCHAR(255),
    payloadtype         VARCHAR(255) NOT NULL,
    timestamp           VARCHAR(255) NOT NULL,
    PRIMARY KEY (aggregateidentifier, sequencenumber, type)
);

CREATE TABLE IF NOT EXISTS voyage (
    voyage_number   VARCHAR(20)  NOT NULL PRIMARY KEY,
    carrier_code    VARCHAR(10)  NOT NULL,
    carrier_name    VARCHAR(200) NOT NULL,
    ship_name       VARCHAR(200) NOT NULL,
    departure_date  TIMESTAMP    NOT NULL,
    arrival_date    TIMESTAMP    NOT NULL,
    origin_unlocode VARCHAR(5)   NOT NULL,
    dest_unlocode   VARCHAR(5)   NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'SCHEDULED',
    registered_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version         BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS carrier_movement (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_number      VARCHAR(20) NOT NULL REFERENCES voyage(voyage_number),
    movement_seq       INTEGER     NOT NULL,
    departure_unlocode VARCHAR(5)  NOT NULL,
    arrival_unlocode   VARCHAR(5)  NOT NULL,
    departure_time     TIMESTAMP   NOT NULL,
    arrival_time       TIMESTAMP   NOT NULL,
    UNIQUE (voyage_number, movement_seq)
);

CREATE TABLE IF NOT EXISTS voyage_accepted_cargo_type (
    voyage_number VARCHAR(20) NOT NULL REFERENCES voyage(voyage_number),
    cargo_type    VARCHAR(16) NOT NULL,
    PRIMARY KEY (voyage_number, cargo_type)
);
