// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cargo struct {
	ID                      int64
	BookingID               string
	ShipperCode             string
	BookingStatus           string
	CargoType               string
	WeightKg                pgtype.Numeric
	SpecOriginUnlocode      string
	SpecDestinationUnlocode string
	SpecArrivalDeadline     pgtype.Date
	BookingAmountValue      int64
	BookingAmountCurrency   string
	CreatedAt               pgtype.Timestamp
	UpdatedAt               pgtype.Timestamp
	HazardousClass          pgtype.Text
	UnNumber                pgtype.Text
	ProperShippingName      pgtype.Text
	MinTemperature          pgtype.Numeric
	MaxTemperature          pgtype.Numeric
	TemperatureUnit         pgtype.Text
	RoutingStatus           string
	TransportStatus         string
	TrackingNumber          pgtype.Text
}

type CarrierMovement struct {
	ID                        int64
	VoyageID                  int64
	DepartureLocationUnlocode string
	ArrivalLocationUnlocode   string
	DepartureDate             pgtype.Timestamp
	ArrivalDate               pgtype.Timestamp
	SeqNumber                 int32
	CreatedAt                 pgtype.Timestamp
	UpdatedAt                 pgtype.Timestamp
}

type CustomsDeclaration struct {
	ID                 int64
	HandlingActivityID int64
	DeclarationNumber  string
	Status             string
	DeclaredAt         pgtype.Timestamp
	ClearedAt          pgtype.Timestamp
	CreatedAt          pgtype.Timestamp
}

type Estimate struct {
	ID                  int64
	EstimateID          pgtype.UUID
	OriginUnlocode      string
	DestinationUnlocode string
	ArrivalDeadline     pgtype.Date
	CargoType           string
	WeightKg            pgtype.Numeric
	Status              string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type HandlingActivity struct {
	ID                    int64
	BookingID             string
	EventType             string
	EventCompletionTime   pgtype.Timestamp
	LocationUnlocode      string
	VoyageNumber          pgtype.Text
	ConsigneeConfirmation pgtype.Text
	OperatorName          pgtype.Text
	CreatedAt             pgtype.Timestamp
}

type Leg struct {
	ID                     int64
	CargoID                int64
	VoyageNumber           string
	LoadLocationUnlocode   string
	UnloadLocationUnlocode string
	LoadTime               pgtype.Timestamp
	UnloadTime             pgtype.Timestamp
	SeqNumber              int32
}

type Notification struct {
	ID          int64
	CargoID     int64
	ShipperCode string
	Summary     string
	SentAt      pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}

type RouteCandidate struct {
	ID            int64
	EstimateID    int64
	VoyageNumber  string
	TransitDays   int32
	EstimatedCost int64
	SeqNumber     int32
	Waypoints     string
}

type SequenceCounter struct {
	Name  string
	Day   pgtype.Date
	Value int32
}

type Shipper struct {
	ID             int64
	ShipperCode    string
	ShipperType    string
	Name           string
	Email          string
	Phone          pgtype.Text
	Address        pgtype.Text
	ContractNumber pgtype.Text
	DiscountRate   pgtype.Numeric
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type TrackingActivity struct {
	ID              int64
	TrackingNumber  string
	BookingID       string
	TransportStatus string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type TrackingExceptionEvent struct {
	ID               int64
	TrackingID       int64
	ExceptionType    string
	OccurredAt       pgtype.Timestamptz
	EscalationFlag   bool
	Description      pgtype.Text
	ResolvedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamp
	ResolutionNotes  pgtype.Text
	LocationUnlocode pgtype.Text
}

type TrackingHandlingEvent struct {
	ID               int64
	TrackingID       int64
	EventType        string
	TransportStatus  string
	EventTime        pgtype.Timestamp
	LocationUnlocode string
	VoyageNumber     pgtype.Text
	SeqNumber        int32
	CreatedAt        pgtype.Timestamp
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	Enabled   bool
	CreatedAt pgtype.Timestamp
}

type UserRole struct {
	UserID int64
	Role   string
}

type Voyage struct {
	ID                  int64
	VoyageNumber        string
	VesselName          string
	Carrier             string
	SupportedCargoTypes string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}
