// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTrackingActivitiesOnDate = `-- name: CountTrackingActivitiesOnDate :one
SELECT COUNT(*) FROM tracking_activity WHERE tracking_number LIKE $1
`

func (q *Queries) CountTrackingActivitiesOnDate(ctx context.Context, trackingNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, countTrackingActivitiesOnDate, trackingNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrackingHandlingEvents = `-- name: CountTrackingHandlingEvents :one
SELECT COUNT(*) FROM tracking_handling_event WHERE tracking_id = $1
`

func (q *Queries) CountTrackingHandlingEvents(ctx context.Context, trackingID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTrackingHandlingEvents, trackingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrackingActivityByBookingId = `-- name: GetTrackingActivityByBookingId :one
SELECT id, tracking_number, booking_id, transport_status
FROM tracking_activity WHERE booking_id = $1
`

type GetTrackingActivityByBookingIdRow struct {
	ID              int64
	TrackingNumber  string
	BookingID       string
	TransportStatus string
}

func (q *Queries) GetTrackingActivityByBookingId(ctx context.Context, bookingID string) (GetTrackingActivityByBookingIdRow, error) {
	row := q.db.QueryRow(ctx, getTrackingActivityByBookingId, bookingID)
	var i GetTrackingActivityByBookingIdRow
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.BookingID,
		&i.TransportStatus,
	)
	return i, err
}

const getTrackingActivityByNumber = `-- name: GetTrackingActivityByNumber :one
SELECT id, tracking_number, booking_id, transport_status
FROM tracking_activity WHERE tracking_number = $1
`

type GetTrackingActivityByNumberRow struct {
	ID              int64
	TrackingNumber  string
	BookingID       string
	TransportStatus string
}

func (q *Queries) GetTrackingActivityByNumber(ctx context.Context, trackingNumber string) (GetTrackingActivityByNumberRow, error) {
	row := q.db.QueryRow(ctx, getTrackingActivityByNumber, trackingNumber)
	var i GetTrackingActivityByNumberRow
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.BookingID,
		&i.TransportStatus,
	)
	return i, err
}

const insertTrackingActivity = `-- name: InsertTrackingActivity :one
INSERT INTO tracking_activity (tracking_number, booking_id, transport_status)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertTrackingActivityParams struct {
	TrackingNumber  string
	BookingID       string
	TransportStatus string
}

func (q *Queries) InsertTrackingActivity(ctx context.Context, arg InsertTrackingActivityParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTrackingActivity, arg.TrackingNumber, arg.BookingID, arg.TransportStatus)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTrackingHandlingEvent = `-- name: InsertTrackingHandlingEvent :exec
INSERT INTO tracking_handling_event (tracking_id, event_type, transport_status, event_time, location_unlocode, voyage_number, seq_number)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTrackingHandlingEventParams struct {
	TrackingID       int64
	EventType        string
	TransportStatus  string
	EventTime        pgtype.Timestamp
	LocationUnlocode string
	VoyageNumber     pgtype.Text
	SeqNumber        int32
}

func (q *Queries) InsertTrackingHandlingEvent(ctx context.Context, arg InsertTrackingHandlingEventParams) error {
	_, err := q.db.Exec(ctx, insertTrackingHandlingEvent,
		arg.TrackingID,
		arg.EventType,
		arg.TransportStatus,
		arg.EventTime,
		arg.LocationUnlocode,
		arg.VoyageNumber,
		arg.SeqNumber,
	)
	return err
}

const listTrackingHandlingEvents = `-- name: ListTrackingHandlingEvents :many
SELECT event_type, transport_status, event_time, location_unlocode, voyage_number
FROM tracking_handling_event WHERE tracking_id = $1 ORDER BY seq_number
`

type ListTrackingHandlingEventsRow struct {
	EventType        string
	TransportStatus  string
	EventTime        pgtype.Timestamp
	LocationUnlocode string
	VoyageNumber     pgtype.Text
}

func (q *Queries) ListTrackingHandlingEvents(ctx context.Context, trackingID int64) ([]ListTrackingHandlingEventsRow, error) {
	rows, err := q.db.Query(ctx, listTrackingHandlingEvents, trackingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackingHandlingEventsRow
	for rows.Next() {
		var i ListTrackingHandlingEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.TransportStatus,
			&i.EventTime,
			&i.LocationUnlocode,
			&i.VoyageNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrackingTransportStatus = `-- name: UpdateTrackingTransportStatus :exec
UPDATE tracking_activity SET transport_status = $2, updated_at = NOW() WHERE tracking_number = $1
`

type UpdateTrackingTransportStatusParams struct {
	TrackingNumber  string
	TransportStatus string
}

func (q *Queries) UpdateTrackingTransportStatus(ctx context.Context, arg UpdateTrackingTransportStatusParams) error {
	_, err := q.db.Exec(ctx, updateTrackingTransportStatus, arg.TrackingNumber, arg.TransportStatus)
	return err
}
