[package]
name = "cargo-tracker-server"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "cargo-tracker-server"

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tower-sessions = "0.14"
tower-http = { workspace = true, features = ["fs", "trace"] }
shared-kernel = { workspace = true }
interface-web = { workspace = true }
interface-rest = { workspace = true }
infra-persistence = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-livereload = "0.9"

[dev-dependencies]
tower = { workspace = true }
http-body-util = { workspace = true }
