-- 貨物の旅程と経路状態（IT9・US09/US11）
-- カラム定義は docs/design/data-model.md を正典とする。

-- ============================================================
-- 1. 経路状態（cargo.routing_status）
-- ============================================================
--
-- **着手前に実物を確認した**（IT9 タスク 0.3）。data-model.md には定義があるが、
-- V5 のコメントが「Routing Context 実装時」として先送りしており、
-- V1-V9 のいずれにも存在しなかった。
--
-- **`BookingStatus` とは別の軸である**。予約が「経路設計中」であることと、
-- 経路が「決まっている」ことは独立に動く——経路を紐付けても予約は経路設計中の
-- ままであり、確定するのは営業が荷主の承認を得たとき（US13）である。
--
-- **既定値を書く**。既存行（IT4-IT9 で作られた予約）は経路を持たないため
-- `NOT_ROUTED` がそのまま正しい。書かないと NOT NULL 制約で ALTER が失敗する。
ALTER TABLE cargo ADD COLUMN routing_status VARCHAR(30) NOT NULL DEFAULT 'NOT_ROUTED';

-- ============================================================
-- 2. 輸送区間（leg）
-- ============================================================
--
-- 貨物 1 件に対して確定した経路の区間を順に持つ。
--
-- **`voyage_number` に FK を張らない**。Booking と Routing はコンテキストが違い、
-- 参照整合性を DB で縛らない（V5 の `cargo.shipper_id` と同じ判断）。
-- data-model.md は FK として書いているが、実装の前例に合わせる
-- （data-model.md も IT9 で FK なしに揃えた）。
--
-- **`cargo_id` には FK を張る**。同一コンテキストの表であり、
-- 旅程は貨物の一部（値オブジェクト）である。親が消えたら区間も消える。
--
-- **区間は置き換える**。経路の選び直しでは既存の行を削除してから入れ直す——
-- 足す形にすると、古い区間が混ざって連結の検証を通らない旅程ができる。
CREATE TABLE leg (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_id                 BIGINT NOT NULL REFERENCES cargo(id) ON DELETE CASCADE,
    voyage_number            VARCHAR(20) NOT NULL,
    load_location_unlocode   VARCHAR(5) NOT NULL REFERENCES location(unlocode),
    unload_location_unlocode VARCHAR(5) NOT NULL REFERENCES location(unlocode),
    load_time                TIMESTAMP,
    unload_time              TIMESTAMP,
    seq_number               INTEGER NOT NULL,
    created_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (cargo_id, seq_number)
);

CREATE INDEX idx_leg_cargo_id ON leg(cargo_id);
