-- 貨物予約（IT4・US04）
-- カラム定義は docs/design/data-model.md を正典とする

-- 貨物。予約の中心となる集約。
--
-- **IT4 のスコープに必要なカラムだけを作る**。将来必要になるカラム
-- （transport_status・routing_status・booking_amount_*・consignee_*・tracking_number・
-- 危険物申告・温度管理条件）は、それを使うイテレーションで追加する。
-- 「後で必要になるから今作る」は禁止（docs/development/development_strategy.md）。
--
-- shipper_id に外部キーを張らない。Booking と Shipper は別コンテキストであり、
-- DB 外部キーによる強結合は将来のサービス分割を妨げる
-- （data-model.md「5. コンテキスト間の参照整合性」）。整合性は
-- ShipperExistenceChecker ACL がアプリケーション層で保証する。
--
-- booking_id は VARCHAR(20)。IT1 で作成済みの tracking_activity.booking_id と
-- 同じ型でなければ突合できない。
CREATE TABLE cargo (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id           VARCHAR(20)   NOT NULL UNIQUE,  -- BK-XXXXXXXX 形式
    shipper_id           VARCHAR(36)   NOT NULL,          -- shipper.shipper_id と同じ値域（FK なし）
    cargo_type           VARCHAR(30)   NOT NULL,          -- GENERAL / HAZARDOUS / REFRIGERATED
    weight               NUMERIC(10,3) NOT NULL,
    origin_unlocode      VARCHAR(5)    NOT NULL REFERENCES location(unlocode),
    destination_unlocode VARCHAR(5)    NOT NULL REFERENCES location(unlocode),
    arrival_deadline     DATE          NOT NULL,
    booking_status       VARCHAR(30)   NOT NULL DEFAULT 'PRELIMINARY',
    dimension_length     NUMERIC(10,3),
    dimension_width      NUMERIC(10,3),
    dimension_height     NUMERIC(10,3),
    quantity             INTEGER,
    description          VARCHAR(500),
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cargo_shipper_id ON cargo(shipper_id);
CREATE INDEX idx_cargo_booking_status ON cargo(booking_status);
