-- 利用者と荷主の紐付け（IT6・TS11）と航海スケジュールの詳細（IT6・US24）
-- カラム定義は docs/design/data-model.md を正典とする。

-- ============================================================
-- 1. 利用者と荷主の紐付け（TS11）
-- ============================================================
--
-- 荷主ロールの利用者が「自分の予約だけ」を見るために要る。
-- IT5 では紐付けが無かったため一覧を絞れず、情報漏洩を止めるには
-- 荷主から予約画面ごと隠すしかなかった。
--
-- **FK を張らない**。`users` は共有（認証）、`shipper` は Shipper Context であり、
-- コンテキスト間の参照整合性は DB 外部キーで縛らない
-- （data-model.md「5. コンテキスト間の参照整合性」・`cargo.shipper_id` と同じ扱い）。
--
-- NULL を許す。営業担当者・経路設計者・管理者は特定の荷主に属さない。
ALTER TABLE users ADD COLUMN shipper_id VARCHAR(36);

CREATE INDEX idx_users_shipper_id ON users(shipper_id);

-- ============================================================
-- 2. 航海スケジュール（US24・US25・US07）
-- ============================================================
--
-- **`voyage` と `carrier_movement` は未作成だった**。data-model.md には
-- 定義があるが、V1 で作ったのは location / tracking 系のみで、
-- `voyage_number` は `tracking_handling_event` の一列として存在するだけだった。
-- 「設計にあるから実装にもある」と考えず、実物を確認すること（IT6 で判明）。
--
-- 船名・運送会社・対応貨物種別は US24 の受入基準 1 が要求する。
-- domain-model.md の Routing Context にはいずれも無かったため、集約とあわせて追加する。
--
-- `capabilities` を 1 列に持つのは、値が 3 種のみで検索が
-- 「この種別に対応しているか」の 1 パターンだからである。別テーブルにすると
-- 結合が増え、得るものが無い。**検索は LIKE ではなく区切り文字を含めた
-- 完全一致で行う**（`LIKE '%GENERAL%'` は将来 `GENERAL_CARGO` のような値が
-- 増えたとき誤一致する）。
CREATE TABLE voyage (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_number VARCHAR(20)  NOT NULL UNIQUE,
    vessel_name   VARCHAR(100) NOT NULL,
    carrier_name  VARCHAR(100) NOT NULL,
    -- 区切り文字で囲んだ集合（例 `,GENERAL,REFRIGERATED,`）。
    -- 前後に区切りを置くのは、`,GENERAL,` の完全一致で誤検出を避けるため
    capabilities  VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_voyage_carrier_name ON voyage(carrier_name);

-- 運送区間。`seq_number` は 1 始まりの連番で、時系列順を表す。
--
-- `location` への外部キーは張る。**同一コンテキスト内の参照**であり、
-- location は共有カーネルである（data-model.md「5. コンテキスト間の参照整合性」）。
CREATE TABLE carrier_movement (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_id                   BIGINT      NOT NULL REFERENCES voyage(id),
    departure_location_unlocode VARCHAR(5)  NOT NULL REFERENCES location(unlocode),
    arrival_location_unlocode   VARCHAR(5)  NOT NULL REFERENCES location(unlocode),
    departure_date              TIMESTAMP   NOT NULL,
    arrival_date                TIMESTAMP   NOT NULL,
    seq_number                  INTEGER     NOT NULL,
    created_at                  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (voyage_id, seq_number)
);

CREATE INDEX idx_carrier_movement_voyage_id ON carrier_movement(voyage_id);
CREATE INDEX idx_carrier_movement_departure ON carrier_movement(departure_location_unlocode);
