<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Db.fs" />
    <Compile Include="UnitOfWork.fs" />
    <Compile Include="Auth.fs" />
    <Compile Include="Views.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Giraffe" Version="8.2.0" />
    <PackageReference Include="Giraffe.ViewEngine" Version="1.4.0" />
    <PackageReference Include="Donald" Version="10.1.0" />
    <PackageReference Include="dbup-core" Version="6.1.1" />
    <PackageReference Include="dbup-sqlite" Version="6.0.4" />
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CargoTracker.Shared\CargoTracker.Shared.fsproj" />
    <ProjectReference Include="..\CargoTracker.Booking\CargoTracker.Booking.fsproj" />
    <ProjectReference Include="..\CargoTracker.Shipper\CargoTracker.Shipper.fsproj" />
    <ProjectReference Include="..\CargoTracker.Routing\CargoTracker.Routing.fsproj" />
    <ProjectReference Include="..\CargoTracker.Tracking\CargoTracker.Tracking.fsproj" />
    <ProjectReference Include="..\CargoTracker.Handling\CargoTracker.Handling.fsproj" />
    <ProjectReference Include="..\CargoTracker.Billing\CargoTracker.Billing.fsproj" />
    <ProjectReference Include="..\CargoTracker.Estimation\CargoTracker.Estimation.fsproj" />
  </ItemGroup>

</Project>
