<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CargoTracker.Application\CargoTracker.Application.csproj" />
    <ProjectReference Include="..\CargoTracker.Domain\CargoTracker.Domain.csproj" />
    <ProjectReference Include="..\CargoTracker.Infrastructure\CargoTracker.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
