/** Billing Context の DI トークン */
export const INVOICE_REPOSITORY = Symbol('INVOICE_REPOSITORY');
export const BILLING_SNAPSHOT_ACL = Symbol('BILLING_SNAPSHOT_ACL');
export const GENERATE_INVOICE_SERVICE = Symbol('GENERATE_INVOICE_SERVICE');
export const BILLING_QUERY_SERVICE = Symbol('BILLING_QUERY_SERVICE');
export const BILLING_NOTIFICATION_PORT = Symbol('BILLING_NOTIFICATION_PORT');
export const PAYMENT_GATEWAY_PORT = Symbol('PAYMENT_GATEWAY_PORT');
export const CONFIRM_PAYMENT_SERVICE = Symbol('CONFIRM_PAYMENT_SERVICE');
export const MARK_OVERDUE_SERVICE = Symbol('MARK_OVERDUE_SERVICE');
export const BILLING_EVENT_PUBLISHER = Symbol('BILLING_EVENT_PUBLISHER');
