sonar.projectKey=cargo-tracker-5-backend
sonar.projectName=Backend
sonar.sources=authms/src/main,routingms/src/main,gatewayms/src/main,shared/src/main
sonar.tests=authms/src/test,routingms/src/test
sonar.java.binaries=authms/build/classes,routingms/build/classes,gatewayms/build/classes,shared/build/classes
sonar.java.test.binaries=authms/build/classes,routingms/build/classes,gatewayms/build/classes
sonar.coverage.jacoco.xmlReportPaths=authms/build/reports/jacoco/test/jacocoTestReport.xml,routingms/build/reports/jacoco/test/jacocoTestReport.xml,gatewayms/build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/generated/**,**/*Application.java,**/config/**,**/package-info.java
sonar.sourceEncoding=UTF-8
