server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /docs-portal {
        return 301 /docs-portal/;
    }

    location /docs-portal/ {
        try_files $uri $uri/ /docs-portal/index.html;
    }
}
