// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipper_acl.sql

package sqlcgen

import (
	"context"
)

const existsShipperByCode = `-- name: ExistsShipperByCode :one
SELECT EXISTS (
    SELECT 1 FROM shipper WHERE shipper_code = $1
)
`

// Booking Context の ACL 用: 荷主コードで荷主の存在を確認する（読み取りのみ）。
func (q *Queries) ExistsShipperByCode(ctx context.Context, shipperCode string) (bool, error) {
	row := q.db.QueryRow(ctx, existsShipperByCode, shipperCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
