// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existsInvoiceByBookingId = `-- name: ExistsInvoiceByBookingId :one
SELECT EXISTS(SELECT 1 FROM invoice WHERE booking_id = $1)
`

func (q *Queries) ExistsInvoiceByBookingId(ctx context.Context, bookingID string) (bool, error) {
	row := q.db.QueryRow(ctx, existsInvoiceByBookingId, bookingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT invoice_number, booking_id, shipper_code, shipper_type,
       base_amount_value, discount_rate, discount_amount_value, tax_amount_value, total_amount_value,
       currency, payment_status, issued_at, due_date, paid_at
FROM invoice WHERE invoice_number = $1
`

type GetInvoiceByNumberRow struct {
	InvoiceNumber       string
	BookingID           string
	ShipperCode         string
	ShipperType         string
	BaseAmountValue     int32
	DiscountRate        pgtype.Numeric
	DiscountAmountValue int32
	TaxAmountValue      int32
	TotalAmountValue    int32
	Currency            string
	PaymentStatus       string
	IssuedAt            pgtype.Timestamptz
	DueDate             pgtype.Date
	PaidAt              pgtype.Timestamptz
}

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (GetInvoiceByNumberRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByNumber, invoiceNumber)
	var i GetInvoiceByNumberRow
	err := row.Scan(
		&i.InvoiceNumber,
		&i.BookingID,
		&i.ShipperCode,
		&i.ShipperType,
		&i.BaseAmountValue,
		&i.DiscountRate,
		&i.DiscountAmountValue,
		&i.TaxAmountValue,
		&i.TotalAmountValue,
		&i.Currency,
		&i.PaymentStatus,
		&i.IssuedAt,
		&i.DueDate,
		&i.PaidAt,
	)
	return i, err
}

const insertInvoice = `-- name: InsertInvoice :exec
INSERT INTO invoice (
    invoice_number, booking_id, shipper_code, shipper_type,
    base_amount_value, discount_rate, discount_amount_value, tax_amount_value, total_amount_value,
    currency, payment_status, issued_at, due_date, paid_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (invoice_number) DO UPDATE SET
    payment_status = EXCLUDED.payment_status,
    paid_at = EXCLUDED.paid_at,
    updated_at = NOW()
`

type InsertInvoiceParams struct {
	InvoiceNumber       string
	BookingID           string
	ShipperCode         string
	ShipperType         string
	BaseAmountValue     int32
	DiscountRate        pgtype.Numeric
	DiscountAmountValue int32
	TaxAmountValue      int32
	TotalAmountValue    int32
	Currency            string
	PaymentStatus       string
	IssuedAt            pgtype.Timestamptz
	DueDate             pgtype.Date
	PaidAt              pgtype.Timestamptz
}

func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, insertInvoice,
		arg.InvoiceNumber,
		arg.BookingID,
		arg.ShipperCode,
		arg.ShipperType,
		arg.BaseAmountValue,
		arg.DiscountRate,
		arg.DiscountAmountValue,
		arg.TaxAmountValue,
		arg.TotalAmountValue,
		arg.Currency,
		arg.PaymentStatus,
		arg.IssuedAt,
		arg.DueDate,
		arg.PaidAt,
	)
	return err
}

const listInvoices = `-- name: ListInvoices :many
SELECT invoice_number, booking_id, shipper_code, shipper_type,
       base_amount_value, discount_rate, discount_amount_value, tax_amount_value, total_amount_value,
       currency, payment_status, issued_at, due_date, paid_at
FROM invoice ORDER BY issued_at DESC, id DESC
`

type ListInvoicesRow struct {
	InvoiceNumber       string
	BookingID           string
	ShipperCode         string
	ShipperType         string
	BaseAmountValue     int32
	DiscountRate        pgtype.Numeric
	DiscountAmountValue int32
	TaxAmountValue      int32
	TotalAmountValue    int32
	Currency            string
	PaymentStatus       string
	IssuedAt            pgtype.Timestamptz
	DueDate             pgtype.Date
	PaidAt              pgtype.Timestamptz
}

func (q *Queries) ListInvoices(ctx context.Context) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.InvoiceNumber,
			&i.BookingID,
			&i.ShipperCode,
			&i.ShipperType,
			&i.BaseAmountValue,
			&i.DiscountRate,
			&i.DiscountAmountValue,
			&i.TaxAmountValue,
			&i.TotalAmountValue,
			&i.Currency,
			&i.PaymentStatus,
			&i.IssuedAt,
			&i.DueDate,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInvoiceSequence = `-- name: NextInvoiceSequence :one
INSERT INTO sequence_counter (name, day, value)
VALUES ($1, $2, 1)
ON CONFLICT (name, day) DO UPDATE SET value = sequence_counter.value + 1
RETURNING value
`

type NextInvoiceSequenceParams struct {
	Name string
	Day  pgtype.Date
}

func (q *Queries) NextInvoiceSequence(ctx context.Context, arg NextInvoiceSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextInvoiceSequence, arg.Name, arg.Day)
	var value int32
	err := row.Scan(&value)
	return value, err
}
