// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipper_acl.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShipperContract = `-- name: GetShipperContract :one
SELECT shipper_type, discount_rate
FROM shipper WHERE shipper_code = $1
`

type GetShipperContractRow struct {
	ShipperType  string
	DiscountRate pgtype.Numeric
}

// Billing → Shipper の ACL（業務識別子 shipper_code で契約割引率を直読・ADR-0005 先例）。
func (q *Queries) GetShipperContract(ctx context.Context, shipperCode string) (GetShipperContractRow, error) {
	row := q.db.QueryRow(ctx, getShipperContract, shipperCode)
	var i GetShipperContractRow
	err := row.Scan(&i.ShipperType, &i.DiscountRate)
	return i, err
}
