-- IT6: Tracking Context 例外イベント（US19 遅延・US20 破損/紛失・CUSTOMS_HOLD 自動登録）
-- 出典: docs/development/iteration_plan-6.md グループ 3/4、docs/design/domain-model.md（TrackingExceptionEvent）。
-- status_before_exception は「例外発生前の状態に復帰」を履歴再導出なしで実現するための永続列
-- （過去教訓「集約状態の再導出禁止」に従う）。reported_at 等は対応報告（US19-4/5）の履歴列。

-- Up Migration

CREATE TABLE tracking_exception_event (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id               BIGINT NOT NULL REFERENCES tracking_activity(id) ON DELETE CASCADE,
    exception_type            VARCHAR(50) NOT NULL,
    occurred_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    escalation_flag           BOOLEAN NOT NULL DEFAULT FALSE,
    location_unlocode         VARCHAR(5) REFERENCES location(unlocode),
    description               VARCHAR(500),
    status_before_exception   VARCHAR(30) NOT NULL,
    resolved_at               TIMESTAMP WITH TIME ZONE,
    resolution_notes          TEXT,
    reported_at               TIMESTAMP WITH TIME ZONE,
    new_estimated_arrival     TIMESTAMP WITH TIME ZONE,
    report_notes              TEXT,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
