-- IT7: Billing Context 請求書・請求明細・支払記録（US21 請求書発行・US22 精算）
-- 出典: docs/development/iteration_plan-7.md グループ 2、docs/design/data-model.md（invoice / invoice_line_item / payment）。
-- invoice.booking_id は UNIQUE 制約で二重請求を防止する。booking_id の BC 間参照は DB FK を張らない方針に従う。

-- Up Migration

CREATE TABLE invoice (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number            VARCHAR(30) NOT NULL UNIQUE,
    booking_id                UUID NOT NULL UNIQUE,
    -- 荷主参照（BC 間参照。法人判定 isCorporate を復元するため種別も保持）
    shipper_id                VARCHAR(100) NOT NULL,
    shipper_type              VARCHAR(30) NOT NULL,
    -- 基本料金（割引・消費税の算出根拠。集約状態の再導出禁止に従い明示保持）
    base_amount_value         INTEGER NOT NULL,
    base_amount_currency      VARCHAR(3) NOT NULL,
    total_amount_value        INTEGER NOT NULL,
    total_amount_currency     VARCHAR(3) NOT NULL,
    tax_rate                  NUMERIC(5,4) NOT NULL DEFAULT 0.1000,
    tax_amount                NUMERIC(15,2) NOT NULL DEFAULT 0,
    payment_status            VARCHAR(30) NOT NULL,
    issued_at                 TIMESTAMP WITH TIME ZONE,
    due_date                  DATE,
    discount_amount_value     INTEGER,
    discount_amount_currency  VARCHAR(3),
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE invoice_line_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id     BIGINT NOT NULL REFERENCES invoice(id) ON DELETE CASCADE,
    description    VARCHAR(200) NOT NULL,
    amount_value   INTEGER NOT NULL,
    amount_currency VARCHAR(3) NOT NULL,
    seq_number     INTEGER NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE payment (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id             BIGINT NOT NULL REFERENCES invoice(id) ON DELETE CASCADE,
    paid_amount_value      INTEGER NOT NULL,
    paid_amount_currency   VARCHAR(3) NOT NULL,
    paid_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    payment_method         VARCHAR(30) NOT NULL,
    transaction_reference  VARCHAR(100),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
