// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notification (cargo_id, shipper_code, summary, sent_at)
VALUES ($1, $2, $3, $4)
`

type InsertNotificationParams struct {
	CargoID     int64
	ShipperCode string
	Summary     string
	SentAt      pgtype.Timestamp
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.CargoID,
		arg.ShipperCode,
		arg.Summary,
		arg.SentAt,
	)
	return err
}

const listNotificationsByBookingId = `-- name: ListNotificationsByBookingId :many
SELECT n.shipper_code, n.summary, n.sent_at
FROM notification n
JOIN cargo c ON c.id = n.cargo_id
WHERE c.booking_id = $1
ORDER BY n.sent_at DESC
`

type ListNotificationsByBookingIdRow struct {
	ShipperCode string
	Summary     string
	SentAt      pgtype.Timestamp
}

func (q *Queries) ListNotificationsByBookingId(ctx context.Context, bookingID string) ([]ListNotificationsByBookingIdRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsByBookingId, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsByBookingIdRow
	for rows.Next() {
		var i ListNotificationsByBookingIdRow
		if err := rows.Scan(&i.ShipperCode, &i.Summary, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
