// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handling.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertHandlingActivity = `-- name: InsertHandlingActivity :one
INSERT INTO handling_activity (booking_id, event_type, event_completion_time, location_unlocode, voyage_number, consignee_confirmation, operator_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertHandlingActivityParams struct {
	BookingID             string
	EventType             string
	EventCompletionTime   pgtype.Timestamp
	LocationUnlocode      string
	VoyageNumber          pgtype.Text
	ConsigneeConfirmation pgtype.Text
	OperatorName          pgtype.Text
}

func (q *Queries) InsertHandlingActivity(ctx context.Context, arg InsertHandlingActivityParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertHandlingActivity,
		arg.BookingID,
		arg.EventType,
		arg.EventCompletionTime,
		arg.LocationUnlocode,
		arg.VoyageNumber,
		arg.ConsigneeConfirmation,
		arg.OperatorName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listHandlingActivitiesByBookingId = `-- name: ListHandlingActivitiesByBookingId :many
SELECT booking_id, event_type, event_completion_time, location_unlocode, voyage_number, consignee_confirmation, operator_name
FROM handling_activity WHERE booking_id = $1 ORDER BY event_completion_time
`

type ListHandlingActivitiesByBookingIdRow struct {
	BookingID             string
	EventType             string
	EventCompletionTime   pgtype.Timestamp
	LocationUnlocode      string
	VoyageNumber          pgtype.Text
	ConsigneeConfirmation pgtype.Text
	OperatorName          pgtype.Text
}

func (q *Queries) ListHandlingActivitiesByBookingId(ctx context.Context, bookingID string) ([]ListHandlingActivitiesByBookingIdRow, error) {
	rows, err := q.db.Query(ctx, listHandlingActivitiesByBookingId, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandlingActivitiesByBookingIdRow
	for rows.Next() {
		var i ListHandlingActivitiesByBookingIdRow
		if err := rows.Scan(
			&i.BookingID,
			&i.EventType,
			&i.EventCompletionTime,
			&i.LocationUnlocode,
			&i.VoyageNumber,
			&i.ConsigneeConfirmation,
			&i.OperatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
