-- IT2: Shared Domain（location）+ Estimation Context（estimate/route_candidate）+ Booking Context（cargo）
-- 出典: docs/design/data-model.md。荷受人カラム（consignee_*）は US04/US05 のため本 IT で前倒し追加（IT2 計画 注 1）。

-- Up Migration

-- Shared Domain
CREATE TABLE location (
    id            BIGSERIAL PRIMARY KEY,
    unlocode      VARCHAR(5)   NOT NULL UNIQUE,   -- UN/LOCODE（例: JPTYO）
    name          VARCHAR(100) NOT NULL,
    country_code  VARCHAR(2),
    time_zone     VARCHAR(50),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Estimation Context
CREATE TABLE estimate (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id           UUID NOT NULL UNIQUE,
    origin_unlocode       VARCHAR(5)  NOT NULL,
    destination_unlocode  VARCHAR(5)  NOT NULL,
    arrival_deadline      DATE        NOT NULL,
    cargo_type            VARCHAR(30) NOT NULL,
    weight_kg             NUMERIC(10,3) NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE route_candidate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id     BIGINT NOT NULL REFERENCES estimate(id) ON DELETE CASCADE,
    voyage_number   VARCHAR(20) NOT NULL,
    transit_port    VARCHAR(5),
    transit_days    INT NOT NULL,
    estimated_cost  NUMERIC(12,2) NOT NULL,
    rank            INT NOT NULL DEFAULT 0
);

-- Booking Context
CREATE TABLE cargo (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id            UUID NOT NULL UNIQUE,
    shipper_id            BIGINT NOT NULL REFERENCES shipper(id),
    cargo_type            VARCHAR(30) NOT NULL DEFAULT 'GENERAL',
    weight                NUMERIC(10,3) NOT NULL CHECK (weight > 0),
    origin_unlocode       VARCHAR(5) NOT NULL,
    destination_unlocode  VARCHAR(5) NOT NULL,
    arrival_deadline      DATE NOT NULL,
    booking_status        VARCHAR(30) NOT NULL DEFAULT 'PRELIMINARY'
                          CHECK (booking_status IN ('PRELIMINARY','ROUTING_IN_PROGRESS','ROUTE_PROPOSED','CONFIRMED','TRACKING_ISSUED','IN_TRANSIT','DELIVERED','SETTLED','CANCELLED')),
    -- 荷受人（US04/US05 のため前倒し。data-model の「将来追加予定」から本体へ）
    consignee_name        VARCHAR(200),
    consignee_email       VARCHAR(200),
    consignee_address     VARCHAR(500),
    -- 貨物仕様（オプション）
    dimension_length      NUMERIC(10,3),
    dimension_width       NUMERIC(10,3),
    dimension_height      NUMERIC(10,3),
    quantity              INTEGER,
    description           VARCHAR(500),
    -- 危険物（HAZARDOUS 時）
    hazardous_class       VARCHAR(10),
    un_number             VARCHAR(10),
    proper_shipping_name  VARCHAR(200),
    -- 温度管理（REFRIGERATED 時）
    min_temperature       NUMERIC(10,3),
    max_temperature       NUMERIC(10,3),
    temperature_unit      VARCHAR(20),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
