-- IT3: Routing Context（voyage / carrier_movement）
-- 出典: docs/development/iteration_plan-3.md、docs/design/data-model.md。
-- ship_name / carrier_name / supported_cargo_types は US24 受入基準に合わせて本 IT で追加する。

-- Up Migration

CREATE TABLE voyage (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_number         VARCHAR(20) NOT NULL UNIQUE,
    ship_name             VARCHAR(100) NOT NULL,
    carrier_name          VARCHAR(100) NOT NULL,
    supported_cargo_types VARCHAR(200) NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE carrier_movement (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_id                    BIGINT NOT NULL REFERENCES voyage(id) ON DELETE CASCADE,
    departure_location_unlocode  VARCHAR(5) NOT NULL REFERENCES location(unlocode),
    arrival_location_unlocode    VARCHAR(5) NOT NULL REFERENCES location(unlocode),
    departure_date               TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_date                 TIMESTAMP WITH TIME ZONE NOT NULL,
    seq_number                   INTEGER NOT NULL,
    created_at                   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT carrier_movement_different_locations
        CHECK (departure_location_unlocode <> arrival_location_unlocode),
    CONSTRAINT carrier_movement_date_order
        CHECK (departure_date <= arrival_date),
    CONSTRAINT carrier_movement_unique_sequence
        UNIQUE (voyage_id, seq_number)
);
