-- IT4: Booking Context の経路紐付け（leg）・追跡番号・通知記録
-- 出典: docs/development/iteration_plan-4.md、docs/design/data-model.md。
-- leg は CargoItinerary を seq_number 順の行集合として表現する。
-- コンテキスト間参照（leg.voyage_number → voyage）はアプリケーション側で整合を保証し DB FK は張らない。

-- Up Migration

CREATE TABLE leg (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_id                  BIGINT NOT NULL REFERENCES cargo(id) ON DELETE CASCADE,
    voyage_number             VARCHAR(20) NOT NULL,
    load_location_unlocode    VARCHAR(5) NOT NULL REFERENCES location(unlocode),
    unload_location_unlocode  VARCHAR(5) NOT NULL REFERENCES location(unlocode),
    load_time                 TIMESTAMP WITH TIME ZONE,
    unload_time               TIMESTAMP WITH TIME ZONE,
    seq_number                INTEGER NOT NULL,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT leg_different_locations
        CHECK (load_location_unlocode <> unload_location_unlocode),
    CONSTRAINT leg_unique_sequence
        UNIQUE (cargo_id, seq_number)
);

-- 追跡番号は発行後に設定するため nullable。発行済のみ一意（部分 UNIQUE インデックス）。
ALTER TABLE cargo ADD COLUMN tracking_number VARCHAR(20);
CREATE UNIQUE INDEX cargo_tracking_number_unique
    ON cargo (tracking_number)
    WHERE tracking_number IS NOT NULL;

-- 経路通知・確定・キャンセル・追跡番号発行の通知送信記録（US12/US13/US14）。
CREATE TABLE notification_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id        UUID NOT NULL,
    notification_type VARCHAR(30) NOT NULL,
    recipient         VARCHAR(200) NOT NULL,
    sent_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
