-- IT5: Handling Context（荷役作業・税関申告）と cargo.routing_status
-- 出典: docs/development/iteration_plan-5.md タスク 2.4、docs/design/data-model.md。
-- booking_id の BC 間参照は DB FK を張らず書き込み側で保証する（data-model 方針）。

-- Up Migration

CREATE TABLE handling_activity (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id             UUID NOT NULL,
    event_type             VARCHAR(30) NOT NULL,
    event_completion_time  TIMESTAMP WITH TIME ZONE NOT NULL,
    location_unlocode      VARCHAR(5) NOT NULL REFERENCES location(unlocode),
    voyage_number          VARCHAR(20),
    operator_name          VARCHAR(200),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE customs_declaration (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handling_activity_id  BIGINT NOT NULL REFERENCES handling_activity(id) ON DELETE CASCADE,
    declaration_number    VARCHAR(50) NOT NULL UNIQUE,
    declared_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    status                VARCHAR(30) NOT NULL,
    cleared_at            TIMESTAMP WITH TIME ZONE,
    remarks               VARCHAR(500),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 経路状態（NOT_ROUTED / ROUTED / MISROUTED）。LOAD/UNLOAD の場所不一致で MISROUTED へ更新される（US15）。
ALTER TABLE cargo ADD COLUMN routing_status VARCHAR(30) NOT NULL DEFAULT 'NOT_ROUTED';

-- 既存の経路紐付け済み予約は ROUTED で埋める。
UPDATE cargo SET routing_status = 'ROUTED'
WHERE id IN (SELECT cargo_id FROM leg);
