-- IT5: Tracking Context（追跡レコード・追跡イベント）
-- 出典: docs/development/iteration_plan-5.md タスク 5.1、docs/design/data-model.md。
-- booking_id の BC 間参照は DB FK を張らず書き込み側で保証する（data-model 方針）。
-- tracking_exception_event（例外）は IT6 スコープのため本マイグレーションでは作成しない。

-- Up Migration

CREATE TABLE tracking_activity (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number   VARCHAR(20) NOT NULL UNIQUE,
    booking_id        UUID NOT NULL,
    transport_status  VARCHAR(30) NOT NULL DEFAULT 'NOT_RECEIVED',
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE tracking_handling_event (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id        BIGINT NOT NULL REFERENCES tracking_activity(id) ON DELETE CASCADE,
    event_type         VARCHAR(30) NOT NULL,
    event_time         TIMESTAMP WITH TIME ZONE NOT NULL,
    location_unlocode  VARCHAR(5) REFERENCES location(unlocode),
    voyage_number      VARCHAR(20),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
