-- 通関状態の変更履歴と、留置の起点（US29 / IT11）。
--
-- 受入基準は「変更履歴（日時・変更者・理由）が申告詳細から**参照できる**」と書いている。
-- 監査ログはアプリのログであり、画面から読めない。参照できるようにするには
-- 永続化した履歴が要る。
--
-- 理由（reason）は履歴側が持つ。申告本体の remarks に持たせると
-- **更新のたびに上書きされ**、「なぜ留置されたのか」が最後の 1 回しか残らない。
CREATE TABLE customs_status_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    declaration_id BIGINT       NOT NULL REFERENCES customs_declaration (id) ON DELETE CASCADE,
    status_from    VARCHAR(30)  NOT NULL,
    status_to      VARCHAR(30)  NOT NULL,
    reason         VARCHAR(500) NOT NULL,
    changed_by     VARCHAR(100) NOT NULL,
    changed_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_customs_history_status
        CHECK (status_from IN ('PENDING', 'CLEARED', 'HELD', 'REJECTED')
           AND status_to   IN ('PENDING', 'CLEARED', 'HELD', 'REJECTED')),
    -- 同じ状態への更新は集約が拒む。ここは最後の砦である
    CONSTRAINT chk_customs_history_changed CHECK (status_from <> status_to)
);

CREATE INDEX idx_customs_history_declaration
    ON customs_status_history (declaration_id, changed_at);

-- いまの留置が始まった日時。
--
-- **解除して再び留置したら数え直す。** 最初の留置日から数え続けると、
-- 審査に戻して 1 日で再留置した申告がいきなり警告になる。
-- 知りたいのは「いま何日止まっているか」である。
--
-- **NULL 可にする。** 留置でない申告は持たないし、この列が無かったころの
-- 行にも値が無い。読み戻す側は NULL を拒んではならない
-- （拒むと荷役ごと読めなくなる。V22 / V23 と同じ判断）。
ALTER TABLE customs_declaration ADD COLUMN held_since TIMESTAMP WITH TIME ZONE;

-- 通関完了の通知（US29「通関済になると荷主・荷受人に通関完了が通知される」）。
-- 通知の実体は記録である（ADR-006）。
ALTER TABLE booking_notification DROP CONSTRAINT chk_notification_type;
ALTER TABLE booking_notification ADD CONSTRAINT chk_notification_type
    CHECK (notification_type IN ('ROUTE_CONFIRMED','SCHEDULE_CHANGED',
                                 'EXCEPTION_RAISED','EXCEPTION_RESOLVED','STATUS_UPDATED',
                                 'CUSTOMS_CLEARED'));
