-- 引取記録の訂正・取り消し（US36）。
--
-- 引取は輸送の終点であり、**誤登録をそのままにすると貨物が届いていないのに
-- 配送完了として扱われる**。IT6 のレビュー H11 が US 化を求めてから
-- 3 イテレーション繰り越した。
--
-- ## 元の記録は消さない
--
-- **訂正・取り消しは「無かったことにする」ことではない。** 誰がいつ何を登録し、
-- 誰がいつ取り消したかが読めなくなると、事故時に経緯を追えない。
-- 荷役の行は残し、取り消された事実を列で表す。
--
-- ## 引取前の状態を永続化する
--
-- 取り消しで戻る先を履歴から再導出しない。**ユニットテストが緑でも、
-- リクエストをまたぐと誤った状態に復帰する**（tracking_exception_event の
-- status_before と同じ判断。V1 のコメントを参照）。
--
-- **NULL 可にする。** 列が無かったころの荷役は値を持たない。
ALTER TABLE handling_activity ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE handling_activity ADD COLUMN cancelled_by VARCHAR(200);
-- 引取の直前の輸送状態（取り消しの復帰先）。
ALTER TABLE handling_activity ADD COLUMN transport_status_before VARCHAR(30);

CREATE TABLE handling_correction (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handling_activity_id BIGINT       NOT NULL REFERENCES handling_activity (id),
    -- CANCEL（取り消し）/ CORRECT（訂正）
    request_type         VARCHAR(20)  NOT NULL,
    -- **理由は必須である。** 理由の無い取り消しは、後から見ると
    -- 「なぜ配送完了が取り消されたのか」が誰にも分からない
    reason               VARCHAR(500) NOT NULL,
    -- 訂正で置き換える値（CANCEL では NULL）
    corrected_completion_time TIMESTAMP WITH TIME ZONE,
    corrected_note       VARCHAR(500),
    requested_by         VARCHAR(200) NOT NULL,
    requested_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    -- PENDING / APPROVED / REJECTED
    status               VARCHAR(20)  NOT NULL,
    decided_by           VARCHAR(200),
    decided_at           TIMESTAMP WITH TIME ZONE,
    decision_reason      VARCHAR(500),
    version              BIGINT       NOT NULL DEFAULT 0,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_handling_correction_type
        CHECK (request_type IN ('CANCEL', 'CORRECT')),
    CONSTRAINT chk_handling_correction_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_handling_correction_activity ON handling_correction (handling_activity_id);
CREATE INDEX idx_handling_correction_status ON handling_correction (status);

-- 引取の直前の輸送状態は **追跡が自分で持つ**。
--
-- 取り消しで戻る先を荷役側から渡すと、追跡の状態を他 BC が決めることになる。
-- 履歴からの再導出もしない（**ユニットテストが緑でも、リクエストをまたぐと
-- 誤った状態に復帰する**。tracking_exception_event.status_before と同じ判断）。
ALTER TABLE tracking_activity ADD COLUMN status_before_claim VARCHAR(30);
