-- 督促の記録（IT14 レビュー C3）。
--
-- **督促は「気づくこと」で終わらない。** 支払期限を過ぎた請求書に気づいても、
-- **いつ・誰が・何を伝えたか**が残らなければ、二重に催促するか、
-- 逆に誰も連絡しないまま月をまたぐ。荷主から「連絡は受けていない」と
-- 言われたときに答えるための記録でもある。
--
-- **請求書とは別のテーブルにする。** 督促は 1 通とは限らず、
-- 請求書の不変条件（金額・状態）とは一緒に守るものでもない。
CREATE TABLE invoice_reminder (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT      NOT NULL REFERENCES invoice (id) ON DELETE CASCADE,
    reminded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reminded_by VARCHAR(50) NOT NULL,
    -- 何を伝えたか。**空でよい**（電話で伝えたことだけが事実の場合がある）
    note        VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 請求書詳細で新しい順に読む。
CREATE INDEX idx_invoice_reminder_invoice
    ON invoice_reminder (invoice_id, reminded_at DESC);
