-- 輸送中の予約キャンセルの申請（US30。遷移表 #10）。
--
-- **輸送開始前とは扱いを分ける。** 輸送開始前は営業担当者の操作で即座に
-- キャンセルできる（遷移表 #9）。輸送中は**貨物が船の上にある**ため、
-- どこで降ろすかを決めないままキャンセルすると貨物が宙に浮く。
--
-- **申請ごとに 1 行残す。** 却下された申請も記録であり、荷主は改めて申請できる。
-- 1 つの予約に複数の申請が並ぶ（US36 の handling_correction と同じ形）。
CREATE TABLE booking_cancellation (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- **UUID を持つ**（booking_notification / booking_route_proposal と同じ形）。
    -- 参照整合性は書き込み側で保証する
    booking_id                  UUID         NOT NULL,
    reason                      VARCHAR(500) NOT NULL,
    requested_by                VARCHAR(50)  NOT NULL,
    requested_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    status                      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    -- 申請時点の料率。**承認時に計算し直さない** —
    -- 承認が遅れたことの費用を荷主に負わせない
    fee_rate                    NUMERIC(5, 4) NOT NULL,
    -- 陸揚げ地。**承認のときだけ値を持つ**（却下では降ろさない）
    discharge_location_unlocode VARCHAR(5) REFERENCES location (unlocode),
    decided_by                  VARCHAR(50),
    decided_at                  TIMESTAMP WITH TIME ZONE,
    decision_reason             VARCHAR(500),
    version                     BIGINT       NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_booking_cancellation_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT chk_booking_cancellation_fee_rate
        CHECK (fee_rate >= 0.0000 AND fee_rate <= 1.0000),
    -- **承認したなら陸揚げ地がある。** 降ろす場所の決まらない承認は、
    -- 荷役の現場に行き先の無い荷物を渡すことと同じである
    CONSTRAINT chk_booking_cancellation_discharge
        CHECK (status <> 'APPROVED' OR discharge_location_unlocode IS NOT NULL),
    -- **却下したなら理由がある。** 申請者は次に何をすればよいか分からない
    CONSTRAINT chk_booking_cancellation_rejection
        CHECK (status <> 'REJECTED' OR decision_reason IS NOT NULL)
);

-- 承認待ち一覧（古い順に捌く）と予約詳細の履歴。
CREATE INDEX idx_booking_cancellation_pending
    ON booking_cancellation (status, requested_at);
CREATE INDEX idx_booking_cancellation_booking
    ON booking_cancellation (booking_id, requested_at DESC);
