// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: estimate.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEstimateByEstimateId = `-- name: GetEstimateByEstimateId :one
SELECT id, estimate_id, origin_unlocode, destination_unlocode, arrival_deadline, cargo_type, weight_kg, status
FROM estimate WHERE estimate_id = $1
`

type GetEstimateByEstimateIdRow struct {
	ID                  int64
	EstimateID          pgtype.UUID
	OriginUnlocode      string
	DestinationUnlocode string
	ArrivalDeadline     pgtype.Date
	CargoType           string
	WeightKg            pgtype.Numeric
	Status              string
}

func (q *Queries) GetEstimateByEstimateId(ctx context.Context, estimateID pgtype.UUID) (GetEstimateByEstimateIdRow, error) {
	row := q.db.QueryRow(ctx, getEstimateByEstimateId, estimateID)
	var i GetEstimateByEstimateIdRow
	err := row.Scan(
		&i.ID,
		&i.EstimateID,
		&i.OriginUnlocode,
		&i.DestinationUnlocode,
		&i.ArrivalDeadline,
		&i.CargoType,
		&i.WeightKg,
		&i.Status,
	)
	return i, err
}

const insertEstimate = `-- name: InsertEstimate :one
INSERT INTO estimate (estimate_id, origin_unlocode, destination_unlocode, arrival_deadline, cargo_type, weight_kg, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertEstimateParams struct {
	EstimateID          pgtype.UUID
	OriginUnlocode      string
	DestinationUnlocode string
	ArrivalDeadline     pgtype.Date
	CargoType           string
	WeightKg            pgtype.Numeric
	Status              string
}

func (q *Queries) InsertEstimate(ctx context.Context, arg InsertEstimateParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEstimate,
		arg.EstimateID,
		arg.OriginUnlocode,
		arg.DestinationUnlocode,
		arg.ArrivalDeadline,
		arg.CargoType,
		arg.WeightKg,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRouteCandidate = `-- name: InsertRouteCandidate :exec
INSERT INTO route_candidate (estimate_id, voyage_number, transit_days, estimated_cost, seq_number, waypoints)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRouteCandidateParams struct {
	EstimateID    int64
	VoyageNumber  string
	TransitDays   int32
	EstimatedCost int64
	SeqNumber     int32
	Waypoints     string
}

func (q *Queries) InsertRouteCandidate(ctx context.Context, arg InsertRouteCandidateParams) error {
	_, err := q.db.Exec(ctx, insertRouteCandidate,
		arg.EstimateID,
		arg.VoyageNumber,
		arg.TransitDays,
		arg.EstimatedCost,
		arg.SeqNumber,
		arg.Waypoints,
	)
	return err
}

const listEstimates = `-- name: ListEstimates :many
SELECT id, estimate_id, origin_unlocode, destination_unlocode, arrival_deadline, cargo_type, weight_kg, status
FROM estimate ORDER BY created_at DESC
`

type ListEstimatesRow struct {
	ID                  int64
	EstimateID          pgtype.UUID
	OriginUnlocode      string
	DestinationUnlocode string
	ArrivalDeadline     pgtype.Date
	CargoType           string
	WeightKg            pgtype.Numeric
	Status              string
}

func (q *Queries) ListEstimates(ctx context.Context) ([]ListEstimatesRow, error) {
	rows, err := q.db.Query(ctx, listEstimates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEstimatesRow
	for rows.Next() {
		var i ListEstimatesRow
		if err := rows.Scan(
			&i.ID,
			&i.EstimateID,
			&i.OriginUnlocode,
			&i.DestinationUnlocode,
			&i.ArrivalDeadline,
			&i.CargoType,
			&i.WeightKg,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteCandidates = `-- name: ListRouteCandidates :many
SELECT voyage_number, transit_days, estimated_cost, waypoints
FROM route_candidate WHERE estimate_id = $1 ORDER BY seq_number
`

type ListRouteCandidatesRow struct {
	VoyageNumber  string
	TransitDays   int32
	EstimatedCost int64
	Waypoints     string
}

func (q *Queries) ListRouteCandidates(ctx context.Context, estimateID int64) ([]ListRouteCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listRouteCandidates, estimateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteCandidatesRow
	for rows.Next() {
		var i ListRouteCandidatesRow
		if err := rows.Scan(
			&i.VoyageNumber,
			&i.TransitDays,
			&i.EstimatedCost,
			&i.Waypoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
