// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cargo struct {
	ID                      int64
	BookingID               string
	ShipperCode             string
	BookingStatus           string
	CargoType               string
	WeightKg                pgtype.Numeric
	SpecOriginUnlocode      string
	SpecDestinationUnlocode string
	SpecArrivalDeadline     pgtype.Date
	BookingAmountValue      int64
	BookingAmountCurrency   string
	CreatedAt               pgtype.Timestamp
	UpdatedAt               pgtype.Timestamp
	HazardousClass          pgtype.Text
	UnNumber                pgtype.Text
	ProperShippingName      pgtype.Text
	MinTemperature          pgtype.Numeric
	MaxTemperature          pgtype.Numeric
	TemperatureUnit         pgtype.Text
	RoutingStatus           string
}

type CarrierMovement struct {
	ID                        int64
	VoyageID                  int64
	DepartureLocationUnlocode string
	ArrivalLocationUnlocode   string
	DepartureDate             pgtype.Timestamp
	ArrivalDate               pgtype.Timestamp
	SeqNumber                 int32
	CreatedAt                 pgtype.Timestamp
	UpdatedAt                 pgtype.Timestamp
}

type Estimate struct {
	ID                  int64
	EstimateID          pgtype.UUID
	OriginUnlocode      string
	DestinationUnlocode string
	ArrivalDeadline     pgtype.Date
	CargoType           string
	WeightKg            pgtype.Numeric
	Status              string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type Leg struct {
	ID                     int64
	CargoID                int64
	VoyageNumber           string
	LoadLocationUnlocode   string
	UnloadLocationUnlocode string
	LoadTime               pgtype.Timestamp
	UnloadTime             pgtype.Timestamp
	SeqNumber              int32
}

type RouteCandidate struct {
	ID            int64
	EstimateID    int64
	VoyageNumber  string
	TransitDays   int32
	EstimatedCost int64
	SeqNumber     int32
}

type Shipper struct {
	ID             int64
	ShipperCode    string
	ShipperType    string
	Name           string
	Email          string
	Phone          pgtype.Text
	Address        pgtype.Text
	ContractNumber pgtype.Text
	DiscountRate   pgtype.Numeric
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	Enabled   bool
	CreatedAt pgtype.Timestamp
}

type UserRole struct {
	UserID int64
	Role   string
}

type Voyage struct {
	ID                  int64
	VoyageNumber        string
	VesselName          string
	Carrier             string
	SupportedCargoTypes string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}
