/** Tracking Context の DI トークン */
export const TRACKING_ACTIVITY_REPOSITORY = Symbol('TRACKING_ACTIVITY_REPOSITORY');
export const TRACKING_NOTIFICATION_PORT = Symbol('TRACKING_NOTIFICATION_PORT');
export const TRACKING_SHIPPER_CONTACT_PORT = Symbol('TRACKING_SHIPPER_CONTACT_PORT');
export const TRACKING_ITINERARY_SNAPSHOT_PORT = Symbol('TRACKING_ITINERARY_SNAPSHOT_PORT');
