/** Handling Context の DI トークン */
export const HANDLING_ACTIVITY_REPOSITORY = Symbol('HANDLING_ACTIVITY_REPOSITORY');
export const CARGO_SNAPSHOT_ACL = Symbol('CARGO_SNAPSHOT_ACL');
export const HANDLING_NOTIFICATION_PORT = Symbol('HANDLING_NOTIFICATION_PORT');
export const HANDLING_EVENT_PUBLISHER = Symbol('HANDLING_EVENT_PUBLISHER');
export const HANDLING_SHIPPER_CONTACT_PORT = Symbol('HANDLING_SHIPPER_CONTACT_PORT');
export const CUSTOMS_DECLARATION_REPOSITORY = Symbol('CUSTOMS_DECLARATION_REPOSITORY');
