-- 荷役作業の記録（US15・IT10）
--
-- `tracking_number` で引く（US15 受入基準 1）。荷役作業員が現場で手にしているのは
-- 貨物に貼られた追跡番号であり、予約番号ではない。
--
-- **FK を張らない**。`tracking_activity` は Tracking Context、`voyage` は
-- Routing Context のテーブルであり、コンテキストを越える参照になる
-- （`leg.voyage_number` と同じ判断）。
--
-- `validity` を持つのは、**判定結果を残さないと後から MISROUTED の経緯を追えない**
-- ためである。設計の `handling_activity` には無い列だが、
-- 同じ設計のデシジョンテーブルが判定を要求している。
--
-- 列名は設計（`data-model.md`）と既存の `tracking_handling_event` に揃える
-- （`event_type` / `event_completion_time` / `operator_name`）。
-- 揃っていない方向へ改名しない。
CREATE TABLE handling_activity (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number       VARCHAR(20)  NOT NULL,
    event_type            VARCHAR(30)  NOT NULL,
    event_completion_time TIMESTAMP    NOT NULL,
    location_unlocode     VARCHAR(5)   NOT NULL REFERENCES location(unlocode),
    voyage_number         VARCHAR(20),
    operator_name         VARCHAR(200),
    validity              VARCHAR(20)  NOT NULL,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 履歴は追跡番号で引く。件数が増えるのは荷役の回数分であり、貨物あたりは少ない
CREATE INDEX idx_handling_activity_tracking ON handling_activity(tracking_number);
