-- 例外の発生前の状態（US19・IT12）
--
-- **カラムに永続化する**。解決時の復帰先を履歴から再導出すると、
-- ユニットテストが緑でもクロスリクエストで誤復帰する（記録済みの教訓）。
--
-- `NULL` は「例外中でない」を意味する。既定値を置かない——
-- 「まだ例外になっていない」と「復帰先が読めない」を区別する必要がある。
ALTER TABLE tracking_activity ADD COLUMN status_before_exception VARCHAR(30);

-- 追跡例外（US19・IT12）
--
-- 設計（`data-model.md`）の定義に **`location_unlocode` と `revised_arrival`** を
-- 加えている。受入基準 1 が発生場所を、受入基準 4 が新しい到着予定日を要求するためである。
--
-- **解決の記録も同じ行に持つ**。別テーブルにすると「未解決の一覧」が結合になり、
-- 追跡管理者が最初に開く画面が重くなる。
--
-- `escalated` を保存するのは、**後から「なぜエスカレーションされたか」を追える**
-- ようにするためである（判定は 48 時間の閾値。時刻が過ぎれば再計算では再現しない）。
CREATE TABLE tracking_exception_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id       BIGINT       NOT NULL REFERENCES tracking_activity(id),
    exception_type    VARCHAR(50)  NOT NULL,
    occurred_at       TIMESTAMP    NOT NULL,
    location_unlocode VARCHAR(5)   REFERENCES location(unlocode),
    description       VARCHAR(500) NOT NULL,
    escalated         BOOLEAN      NOT NULL DEFAULT FALSE,
    resolved_at       TIMESTAMP,
    resolution_notes  VARCHAR(500),
    revised_arrival   TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 未解決の例外を引く。追跡管理者が最初に見るのは「今どれが困っているか」である
CREATE INDEX idx_tracking_exception_open
    ON tracking_exception_event(tracking_id, resolved_at);
