-- 国際貨物輸送管理システム 初期スキーマ
-- IT1 スコープ: Shared Domain（location）と Tracking Context の読み取り経路に必要なテーブルのみ
-- 他コンテキストのテーブルは、各コンテキストを実装するイテレーションで追加する
-- カラム定義は docs/design/data-model.md を正典とする

-- Shared Domain
CREATE TABLE location (
    unlocode     VARCHAR(5)   PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    country_code VARCHAR(2),
    time_zone    VARCHAR(50),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tracking Context
CREATE TABLE tracking_activity (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number  VARCHAR(20) NOT NULL UNIQUE,
    booking_id       VARCHAR(20) NOT NULL,
    transport_status VARCHAR(30) NOT NULL,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tracking_handling_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id       BIGINT      NOT NULL REFERENCES tracking_activity(id),
    event_type        VARCHAR(30) NOT NULL,
    event_time        TIMESTAMP   NOT NULL,
    location_unlocode VARCHAR(5)  REFERENCES location(unlocode),
    voyage_number     VARCHAR(20),
    created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tracking_event_tracking_id ON tracking_handling_event(tracking_id);
