-- 認証・認可の基盤（IT3・TS03）
-- カラム定義は docs/design/data-model.md を正典とする

-- ユーザー（自作認証機構がログイン時に参照する）
-- 認証の識別子は username。email は通知用であり認証には用いない（docs/design/ui_design.md）
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL UNIQUE,
    email           VARCHAR(200) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,  -- BCrypt ハッシュ（コスト 12）
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    -- ログイン失敗 5 回でロック（30 分自動解除）。docs/design/non_functional.md 4.1
    failed_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until    TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 1 利用者 1 ロールとする。Principal が単一の Role を持ち、認可判定も単一ロール前提の
-- ため、複数行あると「どの行が返るか」で権限が変わる（非決定的な認可）。
-- 兼務が要件になった時点で Principal を複数ロール対応にし、この制約を外す。
CREATE TABLE user_roles (
    user_id BIGINT      NOT NULL REFERENCES users(id),
    role    VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id)
);

-- セッション
-- 同一ユーザーの同時セッション数は 1（ADR-0003）。ログイン時に既存行を削除する。
-- インメモリではなく DB に置くのは、複数タスク構成で別タスクのセッションを
-- 無効化する手段が必要になるためである（docs/design/architecture_backend.md）。
CREATE TABLE sessions (
    session_id       VARCHAR(64) PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users(id),
    csrf_token       VARCHAR(64) NOT NULL,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at       TIMESTAMP   NOT NULL
);

CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
