-- 荷主（IT4・US02 / US03）
-- カラム定義は docs/design/data-model.md を正典とする

-- 荷主。個人・法人の 2 種別を 1 テーブルで表す。
--
-- ドメインモデルは CorporateShipper を Shipper のサブタイプとして描いているが、
-- Flix に継承はない。Shipper 集約が shipper_type と法人固有フィールド（NULL 許容）を持ち、
-- 「CORPORATE なら契約番号・割引率が必須」を集約の不変条件として強制する。
--
-- 業務キー（shipper_id / shipper_code / email）にはそれぞれ UNIQUE を付ける。
-- email の一意はドメインのビジネスルール 2 であり、アプリケーション層の重複判定と
-- DB の制約の両方で守る。同時登録は判定をすり抜けるため、DB 側が最後の砦になる。
CREATE TABLE shipper (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 業務キー。Booking Context は本カラムの値で荷主を参照する（FK は張らない）
    shipper_id      VARCHAR(36)  NOT NULL UNIQUE,
    shipper_code    VARCHAR(20)  NOT NULL UNIQUE,  -- SHP-XXXXXXXX 形式
    shipper_type    VARCHAR(20)  NOT NULL,          -- INDIVIDUAL / CORPORATE
    name            VARCHAR(200) NOT NULL,
    email           VARCHAR(200) NOT NULL UNIQUE,
    phone           VARCHAR(50),
    address         VARCHAR(500),
    -- 法人のみ。割引率の上限は 30%（US03 の受入基準・ドメインモデルのビジネスルール 4）
    contract_number VARCHAR(50),
    discount_rate   NUMERIC(5,4),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_shipper_email ON shipper(email);
