-- 輸送見積（IT8・US01）
-- カラム定義は docs/design/data-model.md を正典とする。

-- ============================================================
-- 1. 見積（estimate）
-- ============================================================
--
-- **着手前に実物を確認した**（IT8 タスク 0.4）。data-model.md には定義があるが、
-- V1-V8 のいずれにも `estimate` / `route_candidate` は存在しなかった。
-- IT6 は `voyage` / `carrier_movement` が「設計にあるから実装にもある」と考え、
-- マイグレーションが失敗して初めて気付いた。
--
-- `estimate_id` は業務キー（`EST-XXXXXXXX` として画面に出る値の元）。
-- サロゲートキー + 業務キー UK は本プロジェクトの規約である
-- （data-model.md「1. サロゲートキーと業務キーの併用」）。
--
-- 重量は `NUMERIC(10,3)`（キログラム）。内部表現はグラムの整数であり、
-- 境界で 1000 倍・1000 分の 1 する（`cargo.weight` と同じ形）。
CREATE TABLE estimate (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id           VARCHAR(36) NOT NULL UNIQUE,
    origin_unlocode       VARCHAR(5) NOT NULL,
    destination_unlocode  VARCHAR(5) NOT NULL,
    arrival_deadline      DATE NOT NULL,
    cargo_type            VARCHAR(30) NOT NULL,
    weight_kg             NUMERIC(10, 3) NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_estimate_created_at ON estimate(created_at);

-- ============================================================
-- 2. ルート候補（route_candidate）
-- ============================================================
--
-- **見積のルート候補は永続化する**。経路割り当て画面（US08）の候補は
-- 都度算出で永続化しないが、**保存する理由が違う**——見積は
-- 「あのとき何と言ったか」を後から確認する必要がある（US01 の利用場面）。
-- 再算出すると、航海が更新された後には別の金額が出る。
--
-- 親が消えたら候補も消える（CASCADE）。候補は見積の一部であり、
-- 単独では意味を持たない値オブジェクトである。
--
-- **`estimate` は同一コンテキストの表**であるため FK を張る。
-- コンテキストをまたぐ参照（`cargo.shipper_id` など）には張らない。
--
-- `transit_port` は経由港を `→` で連結した文字列。直行なら NULL。
-- `voyage_number` も複数区間なら連結する。**候補ごとに 1 行**という
-- データモデルに合わせた形であり、モデル側は List で持つ。
--
-- `rank` は表示順（0 が最良）。並び順を保存するのは、
-- 再読み込みのたびに順序が変わると「さっき上にあった候補」を探せなくなるため。
CREATE TABLE route_candidate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id     BIGINT NOT NULL REFERENCES estimate(id) ON DELETE CASCADE,
    voyage_number   VARCHAR(120) NOT NULL,
    transit_port    VARCHAR(120),
    transit_days    INT NOT NULL,
    estimated_cost  NUMERIC(12, 2) NOT NULL,
    rank            INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_route_candidate_estimate_id ON route_candidate(estimate_id);
