[package]
name = "app-shipper"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
shared-kernel = { workspace = true }
domain-shipper = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
mockall = "0.13"
tokio = { workspace = true }
