-- IT8: 精算（Billing Context・Invoice/Payment 集約）
-- 確定した輸送料金（freight_charge・ADR-0009）から精算書を発行し、消費税を適用して請求金額を
-- 確定する（US23）。入金確認で payment を記録し精算完了、支払期限超過で未払い管理する。
-- 金額は freight_charge・Money（Decimal）と整合させ NUMERIC(15,2) に統一（data-model 反映）。

-- 精算書（Billing Context・集約ルート）
CREATE TABLE invoice (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number         VARCHAR(30)  NOT NULL UNIQUE,   -- INV-<uuid>（業務キー）
    booking_id             VARCHAR(20)  NOT NULL UNIQUE,   -- 予約 1 件に 1 精算書
    charge_total_value     NUMERIC(15,2) NOT NULL,         -- 確定料金（割引後・税抜）
    charge_total_currency  VARCHAR(3)   NOT NULL DEFAULT 'JPY',
    tax_rate               NUMERIC(5,4) NOT NULL DEFAULT 0.1000,  -- 消費税率（10%）
    tax_amount             NUMERIC(15,2) NOT NULL DEFAULT 0,      -- 消費税額
    total_amount_value     NUMERIC(15,2) NOT NULL,         -- 請求金額（税込）
    total_amount_currency  VARCHAR(3)   NOT NULL DEFAULT 'JPY',
    payment_status         VARCHAR(30)  NOT NULL DEFAULT 'PENDING',  -- PENDING/CONFIRMED/OVERDUE/REFUNDED
    issued_at              TIMESTAMP WITH TIME ZONE,
    due_date               DATE,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 精算明細（請求内訳）
CREATE TABLE invoice_line_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT       NOT NULL REFERENCES invoice (id) ON DELETE CASCADE,
    description     VARCHAR(200) NOT NULL,
    amount_value    NUMERIC(15,2) NOT NULL,
    amount_currency VARCHAR(3)   NOT NULL DEFAULT 'JPY',
    seq_number      INT          NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_invoice_line_item_invoice_id ON invoice_line_item (invoice_id);

-- 支払記録（入金確認時に記録）
CREATE TABLE payment (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id            BIGINT       NOT NULL REFERENCES invoice (id) ON DELETE CASCADE,
    paid_amount_value     NUMERIC(15,2) NOT NULL,
    paid_amount_currency  VARCHAR(3)   NOT NULL DEFAULT 'JPY',
    paid_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    payment_method        VARCHAR(30)  NOT NULL,   -- BANK_TRANSFER / CREDIT_CARD
    transaction_reference VARCHAR(100),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payment_invoice_id ON payment (invoice_id);
