-- IT7: 輸送料金（Billing Context・FreightCharge 集約）
-- 引取済予約に対する輸送料金の算出（US21）と法人割引の適用（US22）を永続化する。
-- 「確定した輸送料金」は精算書発行（US23・IT8）の入力となる（invoice とは段階分割・ADR-0009）。
-- 命名・監査カラム（created_at/updated_at TIMESTAMPTZ）は既存規約に統一。

-- 輸送料金（Billing Context・集約ルート）
CREATE TABLE freight_charge (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_id              VARCHAR(40)  NOT NULL UNIQUE,   -- FRC-<uuid>（業務キー）
    booking_id             VARCHAR(20)  NOT NULL UNIQUE,   -- 予約 1 件に 1 料金（二重算出防止）
    base_amount_value      NUMERIC(15,2) NOT NULL,         -- 基本料金
    base_amount_currency   VARCHAR(3)   NOT NULL DEFAULT 'JPY',
    discount_rate          NUMERIC(5,4),                   -- 0.0000〜0.3000（法人割引・個人は NULL）
    discount_amount_value  NUMERIC(15,2),                  -- 割引額（割引なしは NULL）
    total_amount_value     NUMERIC(15,2) NOT NULL,         -- 合計（基本 − 調整 − 割引）
    total_amount_currency  VARCHAR(3)   NOT NULL DEFAULT 'JPY',
    status                 VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',  -- DRAFT / CONFIRMED
    confirmed_at           TIMESTAMP WITH TIME ZONE,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 料金調整（例外時の減額・補償費用。US21）
CREATE TABLE freight_charge_adjustment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    freight_charge_id BIGINT       NOT NULL REFERENCES freight_charge (id) ON DELETE CASCADE,
    reason            VARCHAR(30)  NOT NULL,   -- DELAY_REDUCTION / DAMAGE_COMPENSATION
    amount_value      NUMERIC(15,2) NOT NULL,
    amount_currency   VARCHAR(3)   NOT NULL DEFAULT 'JPY',
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_freight_charge_adjustment_charge_id
    ON freight_charge_adjustment (freight_charge_id);
