-- IT4: 通知（Notification）送信記録
-- 予約ライフサイクルの節目（経路設計依頼・荷主への経路通知・追跡番号発行依頼・
-- キャンセル）で送信した通知を記録する。US06/US12/US13 の「通知送信記録の登録」。
-- コンテキスト間参照（booking_id）は BC 独立方針に従い DB 外部キー制約を張らない
-- （cargo.booking_id を業務キーで参照）。命名・監査カラムは既存テーブルと同一規約。

CREATE TABLE notification (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id        VARCHAR(20)  NOT NULL,  -- cargo.booking_id 業務キー参照（FK なし）
    notification_type VARCHAR(30)  NOT NULL,  -- ROUTE_DESIGN_REQUESTED / ROUTE_NOTIFIED_TO_SHIPPER / TRACKING_ISSUE_REQUESTED / BOOKING_CANCELLED
    recipient_role    VARCHAR(50)  NOT NULL,  -- ROLE_SALES / ROLE_ROUTE_DESIGNER / ROLE_SHIPPER 等
    recipient_email   VARCHAR(200) NOT NULL,
    subject           VARCHAR(200) NOT NULL,
    body              TEXT         NOT NULL,
    sent_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notification_booking_id ON notification (booking_id);
