// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, username, email, password, enabled
FROM users
WHERE username = $1
`

type FindUserByUsernameRow struct {
	ID       int64
	Username string
	Email    string
	Password string
	Enabled  bool
}

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (FindUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i FindUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Enabled,
	)
	return i, err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role FROM user_roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
