CREATE TABLE quotes (
    id                      UUID          NOT NULL,
    quote_number            VARCHAR(20)   NOT NULL,
    origin_locode           VARCHAR(10)   NOT NULL,
    destination_locode      VARCHAR(10)   NOT NULL,
    requested_arrival_date  DATE          NOT NULL,
    cargo_type              VARCHAR(20)   NOT NULL,
    weight_kg               NUMERIC(10,2) NOT NULL,
    created_at              TIMESTAMP     NOT NULL,
    CONSTRAINT pk_quotes PRIMARY KEY (id),
    CONSTRAINT uq_quotes_number UNIQUE (quote_number)
);

CREATE TABLE quote_route_options (
    id              BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    quote_id        UUID          NOT NULL,
    voyage_number   VARCHAR(20)   NOT NULL,
    via_locodes     TEXT          NOT NULL,
    transit_days    INT           NOT NULL,
    estimated_price NUMERIC(12,2) NOT NULL,
    sort_order      INT           NOT NULL DEFAULT 0,
    CONSTRAINT pk_quote_route_options PRIMARY KEY (id),
    CONSTRAINT fk_route_options_quote FOREIGN KEY (quote_id) REFERENCES quotes(id)
);
