rules = [
  OrganizeImports,
  DisableSyntax
]

# Scala 3 では removeUnused は未対応のため無効化する
OrganizeImports.removeUnused = false
OrganizeImports.targetDialect = Scala3
OrganizeImports.groupedImports = Merge

DisableSyntax.noVars = true
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noAsInstanceOf = true
