apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cargo-tracker

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgresql.yaml
  - app.yaml
  - ingress.yaml

images:
  - name: cargo-tracker/app
    newTag: latest
