export const VOYAGE_REPOSITORY = Symbol('VOYAGE_REPOSITORY');
export const ROUTING_BOOKING_CONDITION_READER = Symbol('ROUTING_BOOKING_CONDITION_READER');
export const EXTERNAL_ROUTING_SERVICE = Symbol('EXTERNAL_ROUTING_SERVICE');
