-- IT2: Routing Context（航海スケジュール）
-- Voyage 集約（voyage / carrier_movement / voyage_cargo_type）を新規作成する。
-- 対応貨物種別（supported_cargo_types）は複数値のため子テーブルへ正規化する。

-- Routing Context ------------------------------------------------------------
CREATE TABLE voyage (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_number VARCHAR(20)  NOT NULL UNIQUE,
    vessel_name  VARCHAR(100) NOT NULL,
    carrier      VARCHAR(100) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE carrier_movement (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_id    BIGINT       NOT NULL REFERENCES voyage(id) ON DELETE CASCADE,
    departure_location_unlocode VARCHAR(5) NOT NULL,
    arrival_location_unlocode   VARCHAR(5) NOT NULL,
    departure_date TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_date   TIMESTAMP WITH TIME ZONE NOT NULL,
    seq_number   INTEGER      NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_carrier_movement_voyage_id ON carrier_movement (voyage_id);

CREATE TABLE voyage_cargo_type (
    voyage_id    BIGINT       NOT NULL REFERENCES voyage(id) ON DELETE CASCADE,
    cargo_type   VARCHAR(30)  NOT NULL,
    PRIMARY KEY (voyage_id, cargo_type)
);
