-- IT6: 見積（Estimation）・追跡例外（Tracking Exception）
-- 輸送見積の作成（US01）とルート候補、遅延例外の記録・対応報告（US19）を永続化する。
-- tracking_exception_event は IT5 で繰延した分。命名・監査カラムは既存規約に統一。

-- 見積（Estimation Context・集約ルート）
CREATE TABLE estimate (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id          UUID         NOT NULL UNIQUE,   -- EST-<uuid>（業務キー）
    origin_unlocode      VARCHAR(5)   NOT NULL,
    destination_unlocode VARCHAR(5)   NOT NULL,
    arrival_deadline     DATE         NOT NULL,
    cargo_type           VARCHAR(30)  NOT NULL,          -- GENERAL / HAZARDOUS / REFRIGERATED
    weight_kg            NUMERIC(10,3) NOT NULL,
    status               VARCHAR(20)  NOT NULL DEFAULT 'CREATED',  -- CREATED / EXPIRED
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ルート候補（見積に紐づく概算ルート）
CREATE TABLE route_candidate (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id    BIGINT       NOT NULL REFERENCES estimate (id) ON DELETE CASCADE,
    voyage_number  VARCHAR(20)  NOT NULL,
    transit_port   VARCHAR(5),
    transit_days   INT          NOT NULL,
    estimated_cost NUMERIC(12,2) NOT NULL,
    rank           INT          NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_route_candidate_estimate_id ON route_candidate (estimate_id);

-- 追跡例外イベント（遅延・損傷等。IT6 は遅延のみ。IT5 で繰延した分）
CREATE TABLE tracking_exception_event (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id      BIGINT       NOT NULL REFERENCES tracking_activity (id) ON DELETE CASCADE,
    exception_type   VARCHAR(50)  NOT NULL,   -- DELAY（IT6）/ DAMAGE / LOST / CUSTOMS_HOLD（IT7）
    occurred_at      TIMESTAMP WITH TIME ZONE NOT NULL,  -- DateTime<Utc>（domain）と整合
    location_unlocode VARCHAR(5)  NOT NULL,
    escalation_flag  BOOLEAN      NOT NULL DEFAULT FALSE,
    description      VARCHAR(500),
    resolved_at      TIMESTAMP WITH TIME ZONE,
    resolution_notes TEXT,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tracking_exception_event_tracking_id ON tracking_exception_event (tracking_id);
