-- IT5: 追跡（Tracking）・荷役（Handling）
-- 追跡番号発行（US14）・荷役／引取記録（US15/US16）・貨物状態手動更新（US17）で
-- 生成される追跡活動・追跡イベント・荷役作業を記録する。
-- コンテキスト間参照（booking_id）は BC 独立方針に従い DB 外部キー制約を張らない
-- （cargo.booking_id を業務キーで参照）。命名・監査カラムは既存テーブルと同一規約。
-- 通関申告・追跡例外イベントは IT6 スコープのため本マイグレーションでは作成しない。

-- 追跡レコード（TrackingActivity 集約ルート）
CREATE TABLE tracking_activity (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number  VARCHAR(50)  NOT NULL UNIQUE,  -- TRK-<uuid>
    booking_id       VARCHAR(20)  NOT NULL,         -- cargo.booking_id 業務キー参照（FK なし）
    transport_status VARCHAR(30)  NOT NULL,         -- NOT_RECEIVED / RECEIVED / LOADED / ... / CLAIMED
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tracking_activity_booking_id ON tracking_activity (booking_id);

-- 追跡イベント（時系列の追跡出来事。荷役反映・手動更新の履歴）
CREATE TABLE tracking_handling_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id       BIGINT       NOT NULL REFERENCES tracking_activity (id) ON DELETE CASCADE,
    event_type        VARCHAR(30)  NOT NULL,  -- 結果としての輸送状態（RECEIVED / LOADED / ...）
    event_time        TIMESTAMP WITH TIME ZONE NOT NULL,
    location_unlocode VARCHAR(5)   NOT NULL,
    voyage_number     VARCHAR(20),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tracking_handling_event_tracking_id ON tracking_handling_event (tracking_id);

-- 荷役作業記録（HandlingActivity 集約ルート）
CREATE TABLE handling_activity (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id            VARCHAR(20)  NOT NULL,  -- cargo.booking_id 業務キー参照（FK なし）
    event_type            VARCHAR(30)  NOT NULL,  -- RECEIVE / LOAD / UNLOAD / CLAIM
    event_completion_time TIMESTAMP WITH TIME ZONE NOT NULL,
    location_unlocode     VARCHAR(5)   NOT NULL,
    voyage_number         VARCHAR(20),
    operator_name         VARCHAR(200),
    receipt_confirmation  VARCHAR(200),           -- 引取（CLAIM）時の荷受人確認（署名／確認コード。US16）
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_handling_activity_booking_id ON handling_activity (booking_id);
