-- IT3: 確定経路（Routing Context）
-- 経路候補から選択・確定した経路を永続化する。voyage/carrier_movement と同じ規約
-- （単数形・サロゲート PK + 業務キー UK・子は id 参照・seq_number・*_unlocode）に従う。

CREATE TABLE selected_route (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   VARCHAR(20)  NOT NULL UNIQUE,
    status       VARCHAR(20)  NOT NULL DEFAULT 'SELECTED',
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE selected_route_leg (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selected_route_id BIGINT  NOT NULL REFERENCES selected_route(id) ON DELETE CASCADE,
    voyage_number VARCHAR(20) NOT NULL,
    load_location_unlocode   VARCHAR(5) NOT NULL,
    unload_location_unlocode VARCHAR(5) NOT NULL,
    load_time    TIMESTAMP WITH TIME ZONE NOT NULL,
    unload_time  TIMESTAMP WITH TIME ZONE NOT NULL,
    seq_number   INTEGER      NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_selected_route_leg_route_id ON selected_route_leg (selected_route_id);
