-- IT1 初期スキーマ: Shared Domain / Security / Shipper / Booking（予約基盤）
-- 正典: docs/design/data-model.md の「テーブル定義」節

-- Shared Domain -------------------------------------------------------------
CREATE TABLE location (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unlocode     VARCHAR(5)   NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    country_code VARCHAR(2),
    time_zone    VARCHAR(50),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Security Context ----------------------------------------------------------
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    email      VARCHAR(200) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,  -- bcrypt / argon2 ハッシュ
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE user_roles (
    user_id BIGINT      NOT NULL REFERENCES users(id),
    role    VARCHAR(50) NOT NULL,  -- ROLE_SALES / ROLE_SHIPPER 等
    PRIMARY KEY (user_id, role)
);

-- Shipper Context -----------------------------------------------------------
CREATE TABLE shipper (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shipper_code    VARCHAR(20)  NOT NULL UNIQUE,  -- SHP-XXXXXXXX
    shipper_type    VARCHAR(20)  NOT NULL,          -- INDIVIDUAL / CORPORATE
    name            VARCHAR(200) NOT NULL,
    email           VARCHAR(200) NOT NULL UNIQUE,   -- システム全体で一意
    phone           VARCHAR(50),
    address         VARCHAR(500),
    contract_number VARCHAR(50),                    -- 法人のみ
    discount_rate   NUMERIC(5,4) DEFAULT 0.0000,    -- 0.0000〜0.3000（最大 30%）
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Booking Context -----------------------------------------------------------
CREATE TABLE cargo (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id            VARCHAR(20)  NOT NULL UNIQUE,  -- BKG-XXXXXXXX
    shipper_id            UUID         NOT NULL REFERENCES shipper(id),
    cargo_type            VARCHAR(30)  NOT NULL,          -- GENERAL / HAZARDOUS / REFRIGERATED
    weight                NUMERIC(10,3) NOT NULL CHECK (weight > 0),
    origin_unlocode       VARCHAR(5)   NOT NULL,
    destination_unlocode  VARCHAR(5)   NOT NULL,
    arrival_deadline      DATE         NOT NULL,
    consignee_name        VARCHAR(200) NOT NULL,
    consignee_email       VARCHAR(200) NOT NULL,
    booking_status        VARCHAR(30)  NOT NULL DEFAULT 'PRELIMINARY',
    dimension_length      NUMERIC(10,3),
    dimension_width       NUMERIC(10,3),
    dimension_height      NUMERIC(10,3),
    quantity              INTEGER,
    description           VARCHAR(500),
    hazardous_class       VARCHAR(10),
    un_number             VARCHAR(10),
    proper_shipping_name  VARCHAR(200),
    min_temperature       NUMERIC(10,3),
    max_temperature       NUMERIC(10,3),
    temperature_unit      VARCHAR(20),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
