-- 荷主への通知の送信記録（US12 / IT8）。
--
-- **「送ったつもり」を検知できることが本機能の目的である。** 送信操作だけを実装して
-- 履歴を残さないと、荷主から「聞いていない」と言われたときに確認する手段が無い。
--
-- ADR-006 により外部への送信は行わない（内部シミュレーション）。**通知の実体は記録**であり、
-- このテーブルがその実体そのものである。
--
-- cargo の子テーブルにせず booking_id で参照する（tracking_activity と同じ形）。
-- 参照整合性は書き込み側で保証する（data-model.md の既定）。
CREATE TABLE booking_notification (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      UUID         NOT NULL,
    -- 種別。経路確定・スケジュール変更・例外発生（ui_design.md 予約詳細）。
    -- 本 IT で作るのは ROUTE_CONFIRMED のみで、残りは US25 / US19 で足す
    notification_type VARCHAR(30) NOT NULL,
    recipient_email VARCHAR(200) NOT NULL,
    -- 送った内容そのもの。**組み立て直せるようにせず、送った文面を残す。**
    -- 経路や期限は後から変わるため、いま組み立て直すと「送った内容」と違うものが出る
    content         TEXT         NOT NULL,
    sent_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_by         VARCHAR(50)  NOT NULL,
    -- 失敗も残す。**失敗を残さないと「送ったが届かなかった」を追えない**
    result          VARCHAR(20)  NOT NULL,
    failure_reason  VARCHAR(500),
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_notification_type
        CHECK (notification_type IN ('ROUTE_CONFIRMED', 'SCHEDULE_CHANGED', 'EXCEPTION_RAISED')),
    CONSTRAINT chk_notification_result
        CHECK (result IN ('SUCCEEDED', 'FAILED'))
);

-- 予約詳細は通知履歴を常時表示するため、予約 ID での取得が主経路になる
CREATE INDEX idx_booking_notification_booking ON booking_notification (booking_id, sent_at DESC);
