-- 国際貨物輸送管理システム 初期スキーマ
--
-- 定義の正典は docs/design/data-model.md。本ファイルはその実装である。
--
-- ADR-003: 本ファイルは H2（PostgreSQL 互換モード）と PostgreSQL の
-- 両方で実行される。PostgreSQL 固有の構文はここに書かず、
-- db/migration/postgresql/ に隔離すること。
--
-- 6 つの境界付けられたコンテキスト（Booking / Shipper / Routing / Tracking /
-- Billing / Estimation）と共有ドメイン、支援サブドメインの Security に対応する。
-- コンテキスト間に外部キーは張らない（data-model.md 判断 5）。

-- =====================================================================
-- Shared Domain
-- =====================================================================

CREATE TABLE location (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unlocode   VARCHAR(5)   NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================================
-- Security（支援サブドメイン）
-- =====================================================================

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    email      VARCHAR(200) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    role       VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role)
);

-- =====================================================================
-- Shipper Context
-- =====================================================================

CREATE TABLE shipper (
    id                  UUID PRIMARY KEY,
    shipper_code        VARCHAR(20)  NOT NULL UNIQUE,
    shipper_type        VARCHAR(20)  NOT NULL,
    name                VARCHAR(200) NOT NULL,
    -- US02 の受入基準「同一メールアドレスが既に登録されている場合はエラー」を DB で保証する。
    -- 画面の非同期チェックは同時登録の競合に対して無力である。
    email               VARCHAR(200) NOT NULL UNIQUE,
    phone               VARCHAR(50),
    address_country     CHAR(2)      NOT NULL,
    address_postal_code VARCHAR(20)  NOT NULL,
    address_region      VARCHAR(100) NOT NULL,
    address_city        VARCHAR(100) NOT NULL,
    address_street      VARCHAR(200),
    contract_number     VARCHAR(50),
    discount_rate       NUMERIC(5, 4) NOT NULL DEFAULT 0.0000,
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_shipper_type
        CHECK (shipper_type IN ('INDIVIDUAL', 'CORPORATE')),
    -- 割引率の上限 30% はドメインの不変条件（domain-model.md）。画面と DB の両方で守る。
    CONSTRAINT chk_shipper_discount_rate
        CHECK (discount_rate >= 0.0000 AND discount_rate <= 0.3000),
    CONSTRAINT chk_shipper_corporate_contract
        CHECK (shipper_type <> 'CORPORATE' OR contract_number IS NOT NULL)
);

-- =====================================================================
-- Booking Context
-- =====================================================================

CREATE TABLE cargo (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id              UUID         NOT NULL UNIQUE,
    shipper_id              UUID         NOT NULL REFERENCES shipper (id),
    cargo_type              VARCHAR(30)  NOT NULL,
    weight                  NUMERIC(10, 3) NOT NULL,
    origin_unlocode         VARCHAR(5)   NOT NULL,
    destination_unlocode    VARCHAR(5)   NOT NULL,
    arrival_deadline        DATE         NOT NULL,
    booking_status          VARCHAR(30)  NOT NULL DEFAULT 'PRELIMINARY',
    transport_status        VARCHAR(30),
    routing_status          VARCHAR(30)  NOT NULL DEFAULT 'NOT_ROUTED',
    booking_amount_value    INTEGER,
    booking_amount_currency VARCHAR(3),
    consignee_name          VARCHAR(200),
    consignee_email         VARCHAR(200),
    tracking_number         VARCHAR(20),
    version                 BIGINT       NOT NULL DEFAULT 0,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_cargo_type
        CHECK (cargo_type IN ('GENERAL', 'HAZARDOUS', 'REFRIGERATED')),
    CONSTRAINT chk_cargo_weight CHECK (weight > 0),
    -- 出発地と目的地は異なる（domain-model.md ビジネスルール 2）
    CONSTRAINT chk_cargo_origin_destination
        CHECK (origin_unlocode <> destination_unlocode),
    -- BookingStatus の遷移は domain-model.md「BookingStatus 状態遷移表」が正典。
    -- ここで守るのは値の妥当性のみで、遷移の可否はドメインが判断する。
    CONSTRAINT chk_cargo_booking_status
        CHECK (booking_status IN ('PRELIMINARY', 'ROUTE_PROPOSED', 'CONFIRMED',
                                  'TRACKING_ISSUED', 'IN_TRANSIT', 'DELIVERED',
                                  'SETTLED', 'CANCELLED')),
    CONSTRAINT chk_cargo_routing_status
        CHECK (routing_status IN ('NOT_ROUTED', 'ROUTED', 'MISROUTED'))
);

CREATE INDEX idx_cargo_shipper ON cargo (shipper_id);
CREATE INDEX idx_cargo_booking_status ON cargo (booking_status);
CREATE INDEX idx_cargo_arrival_deadline ON cargo (arrival_deadline);

-- =====================================================================
-- Routing Context
-- =====================================================================

CREATE TABLE voyage (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_number VARCHAR(20) NOT NULL UNIQUE,
    version       BIGINT      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE carrier_movement (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_id                   BIGINT     NOT NULL REFERENCES voyage (id) ON DELETE CASCADE,
    departure_location_unlocode VARCHAR(5) NOT NULL REFERENCES location (unlocode),
    arrival_location_unlocode   VARCHAR(5) NOT NULL REFERENCES location (unlocode),
    departure_date              TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_date                TIMESTAMP WITH TIME ZONE NOT NULL,
    seq_number                  INTEGER    NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_carrier_movement_locations
        CHECK (departure_location_unlocode <> arrival_location_unlocode),
    CONSTRAINT chk_carrier_movement_dates
        CHECK (departure_date < arrival_date)
);

CREATE INDEX idx_carrier_movement_voyage ON carrier_movement (voyage_id, seq_number);

-- 予約に紐づく経路候補の置き場（US09 / US10）。
-- 見積の route_candidate とは目的も生存期間も異なるため統合しない。
CREATE TABLE booking_route_proposal (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id                UUID        NOT NULL UNIQUE,
    origin_unlocode           VARCHAR(5)  NOT NULL REFERENCES location (unlocode),
    destination_unlocode      VARCHAR(5)  NOT NULL REFERENCES location (unlocode),
    arrival_deadline          DATE        NOT NULL,
    -- US10 で期限を延長した場合の差分を荷主通知に含めるため、当初の期限を保持する
    original_arrival_deadline DATE        NOT NULL,
    max_transit_count         INTEGER     NOT NULL DEFAULT 2,
    calculation_count         INTEGER     NOT NULL DEFAULT 1,
    -- 0 は「候補ゼロ」を意味し、経路割り当て待ち一覧に表示される
    candidate_count           INTEGER     NOT NULL DEFAULT 0,
    selected_route_id         BIGINT,
    version                   BIGINT      NOT NULL DEFAULT 0,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE proposed_route (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id             BIGINT      NOT NULL
                            REFERENCES booking_route_proposal (id) ON DELETE CASCADE,
    voyage_number           VARCHAR(20) NOT NULL,
    transit_ports           VARCHAR(200),
    departure_date          TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_date            TIMESTAMP WITH TIME ZONE NOT NULL,
    transit_days            INTEGER     NOT NULL,
    estimated_cost_value    INTEGER     NOT NULL,
    estimated_cost_currency VARCHAR(3)  NOT NULL,
    -- false でも一覧には残し、選択不可の理由として示す
    -- （「なぜあの便が出てこないのか」を確認できなくなるため候補から消さない）
    capacity_available      BOOLEAN     NOT NULL,
    hazardous_allowed       BOOLEAN     NOT NULL,
    refrigerated_allowed    BOOLEAN     NOT NULL,
    deadline_satisfied      BOOLEAN     NOT NULL,
    priority                INTEGER     NOT NULL DEFAULT 0,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 循環参照を避けるため proposed_route 作成後に外部キーを追加する
ALTER TABLE booking_route_proposal
    ADD CONSTRAINT fk_proposal_selected_route
    FOREIGN KEY (selected_route_id) REFERENCES proposed_route (id);

CREATE INDEX idx_proposal_booking ON booking_route_proposal (booking_id);
CREATE INDEX idx_proposed_route_proposal ON proposed_route (proposal_id, priority);

-- 輸送区間（Booking の CargoItinerary に対応）。
-- voyage_number への参照はコンテキストを跨ぐが、data-model.md 判断 5 の
-- 例外として業務キーでの参照を許容している。
CREATE TABLE leg (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_id                 BIGINT     NOT NULL REFERENCES cargo (id) ON DELETE CASCADE,
    voyage_number            VARCHAR(20) NOT NULL,
    load_location_unlocode   VARCHAR(5) NOT NULL REFERENCES location (unlocode),
    unload_location_unlocode VARCHAR(5) NOT NULL REFERENCES location (unlocode),
    load_time                TIMESTAMP WITH TIME ZONE,
    unload_time              TIMESTAMP WITH TIME ZONE,
    seq_number               INTEGER    NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_leg_locations
        CHECK (load_location_unlocode <> unload_location_unlocode)
);

CREATE INDEX idx_leg_cargo ON leg (cargo_id, seq_number);
CREATE INDEX idx_leg_voyage_number ON leg (voyage_number);

-- =====================================================================
-- Tracking Context（handling モジュールを含む — ADR-002）
-- =====================================================================

CREATE TABLE tracking_activity (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number  VARCHAR(20) NOT NULL UNIQUE,
    booking_id       UUID        NOT NULL,
    transport_status VARCHAR(30) NOT NULL,
    version          BIGINT      NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_tracking_transport_status
        CHECK (transport_status IN ('NOT_RECEIVED', 'RECEIVED', 'LOADED',
                                    'ONBOARD_CARRIER', 'UNLOADED', 'AWAITING_CLAIM',
                                    'CLAIMED', 'EXCEPTION', 'UNKNOWN'))
);

CREATE INDEX idx_tracking_activity_booking ON tracking_activity (booking_id);

CREATE TABLE tracking_handling_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id       BIGINT      NOT NULL
                      REFERENCES tracking_activity (id) ON DELETE CASCADE,
    event_type        VARCHAR(30) NOT NULL,
    event_time        TIMESTAMP WITH TIME ZONE NOT NULL,
    location_unlocode VARCHAR(5)  REFERENCES location (unlocode),
    voyage_number     VARCHAR(20),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- タイムライン表示は時系列降順が既定の並び
CREATE INDEX idx_tracking_event_timeline
    ON tracking_handling_event (tracking_id, event_time DESC);

CREATE TABLE tracking_exception_event (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id      BIGINT      NOT NULL
                     REFERENCES tracking_activity (id) ON DELETE CASCADE,
    exception_type   VARCHAR(50) NOT NULL,
    occurred_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    escalation_flag  BOOLEAN     NOT NULL DEFAULT FALSE,
    -- 例外発生直前の TransportStatus。解決時の復帰先をここから読む。
    -- 荷役イベント履歴から再導出すると、ユニットテストが緑でも
    -- リクエストをまたぐと誤った状態に復帰する。
    status_before    VARCHAR(30) NOT NULL,
    description      VARCHAR(500),
    resolved_at      TIMESTAMP WITH TIME ZONE,
    -- CLOB は PostgreSQL に存在せず、TEXT は H2 でも受け付けられる。
    -- common/ に置く DDL は両方で動く構文に限る（ADR-003）。
    resolution_notes TEXT,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tracking_exception_tracking ON tracking_exception_event (tracking_id);

CREATE TABLE handling_activity (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id            UUID        NOT NULL,
    event_type            VARCHAR(30) NOT NULL,
    event_completion_time TIMESTAMP WITH TIME ZONE NOT NULL,
    location_unlocode     VARCHAR(5)  NOT NULL REFERENCES location (unlocode),
    voyage_number         VARCHAR(20),
    operator_name         VARCHAR(200),
    version               BIGINT      NOT NULL DEFAULT 0,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_handling_event_type
        CHECK (event_type IN ('RECEIVE', 'LOAD', 'UNLOAD', 'CUSTOMS', 'CLAIM'))
);

CREATE INDEX idx_handling_activity_booking ON handling_activity (booking_id);
CREATE INDEX idx_handling_activity_time ON handling_activity (event_completion_time DESC);

CREATE TABLE customs_declaration (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handling_activity_id BIGINT      NOT NULL REFERENCES handling_activity (id),
    declaration_number   VARCHAR(50) NOT NULL UNIQUE,
    declared_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    status               VARCHAR(30) NOT NULL,
    cleared_at           TIMESTAMP WITH TIME ZONE,
    remarks              VARCHAR(500),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 通関済でないと引取できない（domain-model.md）。この制約はドメインが守る。
    CONSTRAINT chk_customs_status
        CHECK (status IN ('PENDING', 'CLEARED', 'HELD', 'REJECTED'))
);

CREATE INDEX idx_customs_handling ON customs_declaration (handling_activity_id);
CREATE INDEX idx_customs_status ON customs_declaration (status, declared_at);

-- =====================================================================
-- Billing Context
-- =====================================================================

CREATE TABLE invoice (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number           VARCHAR(30) NOT NULL UNIQUE,
    -- UNIQUE 制約で二重請求を防止する
    booking_id               UUID        NOT NULL UNIQUE,
    -- 金額は最小通貨単位の整数で保持する（data-model.md 判断 3）。
    -- 丸め規則は domain-model.md「金額の丸め規則」が正典。
    base_amount_value        INTEGER     NOT NULL,
    base_amount_currency     VARCHAR(3)  NOT NULL,
    discount_rate            NUMERIC(5, 4) NOT NULL DEFAULT 0,
    tax_rate                 NUMERIC(5, 4) NOT NULL DEFAULT 0.1000,
    tax_amount_value         INTEGER     NOT NULL DEFAULT 0,
    tax_amount_currency      VARCHAR(3)  NOT NULL,
    total_amount_value       INTEGER     NOT NULL,
    total_amount_currency    VARCHAR(3)  NOT NULL,
    payment_status           VARCHAR(30) NOT NULL,
    issued_at                TIMESTAMP WITH TIME ZONE,
    due_date                 DATE,
    discount_amount_value    INTEGER,
    discount_amount_currency VARCHAR(3),
    version                  BIGINT      NOT NULL DEFAULT 0,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_invoice_payment_status
        CHECK (payment_status IN ('PENDING', 'CONFIRMED', 'OVERDUE', 'REFUNDED')),
    CONSTRAINT chk_invoice_discount_rate
        CHECK (discount_rate >= 0.0000 AND discount_rate <= 0.3000)
);

CREATE INDEX idx_invoice_booking ON invoice (booking_id);
CREATE INDEX idx_invoice_overdue ON invoice (payment_status, due_date);

CREATE TABLE invoice_line_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT       NOT NULL REFERENCES invoice (id) ON DELETE CASCADE,
    description     VARCHAR(200) NOT NULL,
    amount_value    INTEGER      NOT NULL,
    amount_currency VARCHAR(3)   NOT NULL,
    seq_number      INTEGER      NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_invoice_line_item_invoice ON invoice_line_item (invoice_id, seq_number);

CREATE TABLE payment (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id            BIGINT      NOT NULL REFERENCES invoice (id),
    paid_amount_value     INTEGER     NOT NULL,
    paid_amount_currency  VARCHAR(3)  NOT NULL,
    paid_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    payment_method        VARCHAR(30) NOT NULL,
    transaction_reference VARCHAR(100),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_payment_invoice ON payment (invoice_id);

-- =====================================================================
-- Estimation Context
-- =====================================================================

CREATE TABLE estimate (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id          UUID        NOT NULL UNIQUE,
    origin_unlocode      VARCHAR(5)  NOT NULL,
    destination_unlocode VARCHAR(5)  NOT NULL,
    arrival_deadline     DATE        NOT NULL,
    cargo_type           VARCHAR(30) NOT NULL,
    weight_kg            NUMERIC(10, 3) NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    version              BIGINT      NOT NULL DEFAULT 0,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_estimate_status CHECK (status IN ('CREATED', 'EXPIRED')),
    CONSTRAINT chk_estimate_locations
        CHECK (origin_unlocode <> destination_unlocode)
);

CREATE TABLE route_candidate (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id             BIGINT      NOT NULL REFERENCES estimate (id) ON DELETE CASCADE,
    voyage_number           VARCHAR(20) NOT NULL,
    transit_port            VARCHAR(5),
    transit_days            INTEGER     NOT NULL,
    estimated_cost_value    INTEGER     NOT NULL,
    estimated_cost_currency VARCHAR(3)  NOT NULL,
    -- rank は SQL の予約語のため priority を用いる
    priority                INTEGER     NOT NULL DEFAULT 0,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_route_candidate_estimate ON route_candidate (estimate_id);
