# heroku プロファイル: Heroku 上のサービス間ルーティング
spring:
  cloud:
    gateway:
      routes:
        - id: authms
          uri: ${AUTHMS_URL}
          predicates:
            - Path=/api/auth/**, /api/v1/users/**
        - id: routingms
          uri: ${ROUTINGMS_URL}
          predicates:
            - Path=/api/v1/voyages/**, /api/v1/routes/**

logging:
  level:
    com.example.gatewayms: INFO
    root: WARN
