// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cargo.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCargo = `-- name: InsertCargo :one
INSERT INTO cargo (
    booking_id, shipper_code, booking_status, cargo_type, weight_kg,
    spec_origin_unlocode, spec_destination_unlocode, spec_arrival_deadline,
    booking_amount_value, booking_amount_currency
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id
`

type InsertCargoParams struct {
	BookingID               string
	ShipperCode             string
	BookingStatus           string
	CargoType               string
	WeightKg                pgtype.Numeric
	SpecOriginUnlocode      string
	SpecDestinationUnlocode string
	SpecArrivalDeadline     pgtype.Date
	BookingAmountValue      int64
	BookingAmountCurrency   string
}

func (q *Queries) InsertCargo(ctx context.Context, arg InsertCargoParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCargo,
		arg.BookingID,
		arg.ShipperCode,
		arg.BookingStatus,
		arg.CargoType,
		arg.WeightKg,
		arg.SpecOriginUnlocode,
		arg.SpecDestinationUnlocode,
		arg.SpecArrivalDeadline,
		arg.BookingAmountValue,
		arg.BookingAmountCurrency,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCargos = `-- name: ListCargos :many
SELECT id, booking_id, shipper_code, booking_status, cargo_type, weight_kg,
       spec_origin_unlocode, spec_destination_unlocode, spec_arrival_deadline,
       booking_amount_value, booking_amount_currency, created_at, updated_at
FROM cargo
ORDER BY id DESC
`

func (q *Queries) ListCargos(ctx context.Context) ([]Cargo, error) {
	rows, err := q.db.Query(ctx, listCargos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cargo
	for rows.Next() {
		var i Cargo
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.ShipperCode,
			&i.BookingStatus,
			&i.CargoType,
			&i.WeightKg,
			&i.SpecOriginUnlocode,
			&i.SpecDestinationUnlocode,
			&i.SpecArrivalDeadline,
			&i.BookingAmountValue,
			&i.BookingAmountCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
