// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cargo.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCargoByBookingId = `-- name: GetCargoByBookingId :one
SELECT id, booking_id, shipper_code, booking_status, cargo_type, weight_kg,
       spec_origin_unlocode, spec_destination_unlocode, spec_arrival_deadline,
       booking_amount_value, booking_amount_currency,
       hazardous_class, un_number, proper_shipping_name,
       min_temperature, max_temperature, temperature_unit,
       created_at, updated_at
FROM cargo
WHERE booking_id = $1
`

type GetCargoByBookingIdRow struct {
	ID                      int64
	BookingID               string
	ShipperCode             string
	BookingStatus           string
	CargoType               string
	WeightKg                pgtype.Numeric
	SpecOriginUnlocode      string
	SpecDestinationUnlocode string
	SpecArrivalDeadline     pgtype.Date
	BookingAmountValue      int64
	BookingAmountCurrency   string
	HazardousClass          pgtype.Text
	UnNumber                pgtype.Text
	ProperShippingName      pgtype.Text
	MinTemperature          pgtype.Numeric
	MaxTemperature          pgtype.Numeric
	TemperatureUnit         pgtype.Text
	CreatedAt               pgtype.Timestamp
	UpdatedAt               pgtype.Timestamp
}

func (q *Queries) GetCargoByBookingId(ctx context.Context, bookingID string) (GetCargoByBookingIdRow, error) {
	row := q.db.QueryRow(ctx, getCargoByBookingId, bookingID)
	var i GetCargoByBookingIdRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ShipperCode,
		&i.BookingStatus,
		&i.CargoType,
		&i.WeightKg,
		&i.SpecOriginUnlocode,
		&i.SpecDestinationUnlocode,
		&i.SpecArrivalDeadline,
		&i.BookingAmountValue,
		&i.BookingAmountCurrency,
		&i.HazardousClass,
		&i.UnNumber,
		&i.ProperShippingName,
		&i.MinTemperature,
		&i.MaxTemperature,
		&i.TemperatureUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCargo = `-- name: InsertCargo :one
INSERT INTO cargo (
    booking_id, shipper_code, booking_status, cargo_type, weight_kg,
    spec_origin_unlocode, spec_destination_unlocode, spec_arrival_deadline,
    booking_amount_value, booking_amount_currency,
    hazardous_class, un_number, proper_shipping_name,
    min_temperature, max_temperature, temperature_unit
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16
)
RETURNING id
`

type InsertCargoParams struct {
	BookingID               string
	ShipperCode             string
	BookingStatus           string
	CargoType               string
	WeightKg                pgtype.Numeric
	SpecOriginUnlocode      string
	SpecDestinationUnlocode string
	SpecArrivalDeadline     pgtype.Date
	BookingAmountValue      int64
	BookingAmountCurrency   string
	HazardousClass          pgtype.Text
	UnNumber                pgtype.Text
	ProperShippingName      pgtype.Text
	MinTemperature          pgtype.Numeric
	MaxTemperature          pgtype.Numeric
	TemperatureUnit         pgtype.Text
}

func (q *Queries) InsertCargo(ctx context.Context, arg InsertCargoParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCargo,
		arg.BookingID,
		arg.ShipperCode,
		arg.BookingStatus,
		arg.CargoType,
		arg.WeightKg,
		arg.SpecOriginUnlocode,
		arg.SpecDestinationUnlocode,
		arg.SpecArrivalDeadline,
		arg.BookingAmountValue,
		arg.BookingAmountCurrency,
		arg.HazardousClass,
		arg.UnNumber,
		arg.ProperShippingName,
		arg.MinTemperature,
		arg.MaxTemperature,
		arg.TemperatureUnit,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCargos = `-- name: ListCargos :many
SELECT id, booking_id, shipper_code, booking_status, cargo_type, weight_kg,
       spec_origin_unlocode, spec_destination_unlocode, spec_arrival_deadline,
       booking_amount_value, booking_amount_currency,
       hazardous_class, un_number, proper_shipping_name,
       min_temperature, max_temperature, temperature_unit,
       created_at, updated_at
FROM cargo
ORDER BY id DESC
`

type ListCargosRow struct {
	ID                      int64
	BookingID               string
	ShipperCode             string
	BookingStatus           string
	CargoType               string
	WeightKg                pgtype.Numeric
	SpecOriginUnlocode      string
	SpecDestinationUnlocode string
	SpecArrivalDeadline     pgtype.Date
	BookingAmountValue      int64
	BookingAmountCurrency   string
	HazardousClass          pgtype.Text
	UnNumber                pgtype.Text
	ProperShippingName      pgtype.Text
	MinTemperature          pgtype.Numeric
	MaxTemperature          pgtype.Numeric
	TemperatureUnit         pgtype.Text
	CreatedAt               pgtype.Timestamp
	UpdatedAt               pgtype.Timestamp
}

func (q *Queries) ListCargos(ctx context.Context) ([]ListCargosRow, error) {
	rows, err := q.db.Query(ctx, listCargos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCargosRow
	for rows.Next() {
		var i ListCargosRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.ShipperCode,
			&i.BookingStatus,
			&i.CargoType,
			&i.WeightKg,
			&i.SpecOriginUnlocode,
			&i.SpecDestinationUnlocode,
			&i.SpecArrivalDeadline,
			&i.BookingAmountValue,
			&i.BookingAmountCurrency,
			&i.HazardousClass,
			&i.UnNumber,
			&i.ProperShippingName,
			&i.MinTemperature,
			&i.MaxTemperature,
			&i.TemperatureUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCargoStatus = `-- name: UpdateCargoStatus :execrows
UPDATE cargo
SET booking_status = $2,
    updated_at = NOW()
WHERE booking_id = $1
`

type UpdateCargoStatusParams struct {
	BookingID     string
	BookingStatus string
}

func (q *Queries) UpdateCargoStatus(ctx context.Context, arg UpdateCargoStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCargoStatus, arg.BookingID, arg.BookingStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
