// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cargo struct {
	ID                      int64
	BookingID               string
	ShipperCode             string
	BookingStatus           string
	CargoType               string
	WeightKg                pgtype.Numeric
	SpecOriginUnlocode      string
	SpecDestinationUnlocode string
	SpecArrivalDeadline     pgtype.Date
	BookingAmountValue      int64
	BookingAmountCurrency   string
	CreatedAt               pgtype.Timestamp
	UpdatedAt               pgtype.Timestamp
}

type Shipper struct {
	ID             int64
	ShipperCode    string
	ShipperType    string
	Name           string
	Email          string
	Phone          pgtype.Text
	Address        pgtype.Text
	ContractNumber pgtype.Text
	DiscountRate   pgtype.Numeric
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
