// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shipper struct {
	ID             int64
	ShipperCode    string
	ShipperType    string
	Name           string
	Email          string
	Phone          pgtype.Text
	Address        pgtype.Text
	ContractNumber pgtype.Text
	DiscountRate   pgtype.Numeric
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
