// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipper.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existsShipperByCode = `-- name: ExistsShipperByCode :one
SELECT EXISTS (
    SELECT 1 FROM shipper WHERE shipper_code = $1
) AS exists
`

func (q *Queries) ExistsShipperByCode(ctx context.Context, shipperCode string) (bool, error) {
	row := q.db.QueryRow(ctx, existsShipperByCode, shipperCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsShipperByEmail = `-- name: ExistsShipperByEmail :one
SELECT EXISTS (
    SELECT 1 FROM shipper WHERE email = $1
) AS exists
`

func (q *Queries) ExistsShipperByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsShipperByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findShipperByCode = `-- name: FindShipperByCode :one
SELECT id, shipper_code, shipper_type, name, email, phone, address, contract_number, discount_rate, created_at, updated_at
FROM shipper
WHERE shipper_code = $1
`

func (q *Queries) FindShipperByCode(ctx context.Context, shipperCode string) (Shipper, error) {
	row := q.db.QueryRow(ctx, findShipperByCode, shipperCode)
	var i Shipper
	err := row.Scan(
		&i.ID,
		&i.ShipperCode,
		&i.ShipperType,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ContractNumber,
		&i.DiscountRate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertShipper = `-- name: InsertShipper :one
INSERT INTO shipper (
    shipper_code, shipper_type, name, email, phone, address, contract_number, discount_rate
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type InsertShipperParams struct {
	ShipperCode    string
	ShipperType    string
	Name           string
	Email          string
	Phone          pgtype.Text
	Address        pgtype.Text
	ContractNumber pgtype.Text
	DiscountRate   pgtype.Numeric
}

func (q *Queries) InsertShipper(ctx context.Context, arg InsertShipperParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertShipper,
		arg.ShipperCode,
		arg.ShipperType,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.ContractNumber,
		arg.DiscountRate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listShippers = `-- name: ListShippers :many
SELECT id, shipper_code, shipper_type, name, email, phone, address, contract_number, discount_rate, created_at, updated_at
FROM shipper
ORDER BY id DESC
`

func (q *Queries) ListShippers(ctx context.Context) ([]Shipper, error) {
	rows, err := q.db.Query(ctx, listShippers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipper
	for rows.Next() {
		var i Shipper
		if err := rows.Scan(
			&i.ID,
			&i.ShipperCode,
			&i.ShipperType,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.ContractNumber,
			&i.DiscountRate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
