-- 貨物予約テーブル（PostgreSQL 方言・US04・data-model IT2 実装状況）
CREATE TABLE cargo (
    id                        BIGSERIAL     PRIMARY KEY,
    booking_id                VARCHAR(20)   NOT NULL,
    shipper_id                BIGINT        NOT NULL REFERENCES shipper(id),
    cargo_type                VARCHAR(30)   NOT NULL,
    weight                    NUMERIC(10,3) NOT NULL,
    origin_unlocode           VARCHAR(5)    NOT NULL,
    destination_unlocode      VARCHAR(5)    NOT NULL,
    arrival_deadline          DATE          NOT NULL,
    booking_status            VARCHAR(30)   NOT NULL DEFAULT 'PRELIMINARY',
    dimension_length          NUMERIC(10,3),
    dimension_width           NUMERIC(10,3),
    dimension_height          NUMERIC(10,3),
    quantity                  INTEGER,
    description               VARCHAR(500),
    hazardous_class           VARCHAR(10),
    un_number                 VARCHAR(10),
    proper_shipping_name      VARCHAR(200),
    min_temperature           NUMERIC(10,3),
    max_temperature           NUMERIC(10,3),
    temperature_unit          VARCHAR(20),
    created_at                TIMESTAMPTZ   NOT NULL,
    updated_at                TIMESTAMPTZ   NOT NULL,
    version                   BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_cargo_booking_id UNIQUE (booking_id),
    CONSTRAINT ck_cargo_weight_positive CHECK (weight > 0),
    CONSTRAINT ck_cargo_quantity_positive CHECK (quantity IS NULL OR quantity >= 1)
);
